### ISSUE TITLE
another Fault

### ISSUE THREAD

**Issue by criticallimit** [gcobb321/icloud3_v3#112]
here the log:

Logger: icloud3
Source: helpers/entity.py:578 
First occurred: 23:30:00 (4 occurrences) 
Last logged: 23:32:06

Attribute hass is None for <DeviceSensor: icloud3_event_log>
Traceback (most recent call last):
  File "/config/custom_components/icloud3/sensor.py", line 1236, in async_update_sensor
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 578, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <DeviceSensor: icloud3_event_log>

**Comment by gcobb321** [comment]
Added more error checking in b16
