### ISSUE TITLE
500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by steuerzentrale** [gcobb321/icloud3_v3#122]
Hi there

first of all many thanks for this nice piece of software. I am running Home Assistant 2023.5.2 on a Pi 4. When I try to install iCloud3 I get the following error: 500 Internal Server Error Server got itself in trouble

<img width="471" alt="Bildschirmfoto 2023-05-09 um 17 19 40" src="https://github.com/gcobb321/icloud3_v3/assets/75168550/6cc5786c-9d7c-4d11-bbc5-6416a277c021">

In the logs I get the following information:
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: aiohttp.server
Source: custom_components/icloud3/config_flow.py:450
Integration: iCloud3 (documentation, issues)
First occurred: 17:18:23 (1 occurrences)
Last logged: 17:18:23

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 845, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 873, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/icloud3/config_flow.py", line 450, in async_step_user
    if Gb.hass.data.get(DOMAIN):
AttributeError: 'NoneType' object has no attribute 'data'

details
 Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest 

I have no clue nor knowledge what it means in detail. Could you please have a look at the log and point me into the right direction? I even restored from a two old days backup to rule out any cache issues etc. but it didnt help.

appreciate any help

all the best

Andrew

**Comment by gcobb321** [comment]
What version of v3 are you running?

**Comment by steuerzentrale** [comment]
sorry its [iCloud3 v3, beta 16a (5/7/2023)](https://github.com/gcobb321/icloud3_v3/releases/tag/v3.0.0-beta-16)

**Comment by gcobb321** [comment]
Does the _icloud3_main.py_ file exist in the _icloud3_ directory? If not, download the Release zip file again, unzip, restart HA and try again. (That file was not in the original Release for about 12 
Was this the first time you installed iCloud3 v3?
Has it ever been up and running and configured?

**Comment by DamageDoctor** [comment]
Had the same issue with 16a. Downloaded 15 and installed that which worked. Will test 16a over the top of 15 soon to see if it works.

**Comment by DamageDoctor** [comment]
v15 allowed me to complete initial configuration and then I installed 16a back over the top. This appears to be working now. Guessing something else is missing in the 16a asset.
