### ISSUE TITLE
'Unknown error occurred' when trying to add a device with configuration wizard

### ISSUE THREAD

**Issue by DerDon1302** [gcobb321/icloud3_v3#123]
I always get an unknown error message when trying to add a device with the configuration wizard. Every other menu of the configuration wizard can be opened without any problem. Logging in to my iCloud account worked too.
I am running the latest Home Assistant and Home Assistant OS version and also deleted the beta 16a and installed beta 15...same problem on both versions.

![SCR-20230510-myl](https://github.com/gcobb321/icloud3_v3/assets/102979918/9c619b1a-dad1-4ffb-8f13-1e49caa84d39)

**Comment by gcobb321** [comment]
You will also get that error on the 'display_as' screen on menu page 2. It has to do with more than 5 devices being tracked and has already been fixed in b16b to be uploaded this afternoon.

**Comment by DerDon1302** [comment]
> You will also get that error on the 'display_as' screen on menu page 2. It has to do with more than 5 devices being tracked and has already been fixed in b16b to be uploaded this afternoon.

Thanks for your quick response.
I don't have any devices set up yet and I can open the 'display text as' screen without any problem. Maybe a different error then? 

![SCR-20230510-nht](https://github.com/gcobb321/icloud3_v3/assets/102979918/023b9024-ac44-4492-aeca-14caff3e8910)

**Comment by gcobb321** [comment]
Beta 16b - 5/10/2023 (11:07:33am US EDT)
...................

Enter Zone - Fixed a problem where an iOS App Enter Zone trigger was being not being processed. There was a test for entering a track_from_zone (Home) that was was being delayed. The next time the trigger was checked, the update was not being processed since the data had not changed when it should have been processed on the initial trigger.

Stationary Zone - Added another check to make sure the Stationary Zone will not be created when it is close to another zone. The gps accuracy + 25m is now also used in the minimum distance calculation.

Configuration Wizard - Fixed a problem displaying the 'Next Page' on the Update Devices and Display-Text As screens.

Here is an updated b16b

[icloud3_v3-beta-16b.zip](https://github.com/gcobb321/icloud3_v3/files/11443561/icloud3_v3-beta-16b.zip)

**Comment by DerDon1302** [comment]
> Beta 16b - 5/10/2023 (11:07:33am US EDT) ...................
> 
> Enter Zone - Fixed a problem where an iOS App Enter Zone trigger was being not being processed. There was a test for entering a track_from_zone (Home) that was was being delayed. The next time the trigger was checked, the update was not being processed since the data had not changed when it should have been processed on the initial trigger.
> 
> Stationary Zone - Added another check to make sure the Stationary Zone will not be created when it is close to another zone. The gps accuracy + 25m is now also used in the minimum distance calculation.
> 
> Configuration Wizard - Fixed a problem displaying the 'Next Page' on the Update Devices and Display-Text As screens.
> 
> Here is an updated b16b
> 
> [icloud3_v3-beta-16b.zip](https://github.com/gcobb321/icloud3_v3/files/11443561/icloud3_v3-beta-16b.zip)

Sadly still the same error as before the update shows up.

**Comment by gcobb321** [comment]
Are there any error messages in the home-assistant.log?

**Comment by DerDon1302** [comment]
> Are there any error messages in the home-assistant.log? I just deleted all my devices, went to the Update Devices screen and it worked OK. Displayed the no devices available for tracking message, selected the screen and all OK. Did you verify your icloud account username and password on the iCloud Account Credentials screen?

Yes I verified my account via the code sent to my iphone.
Weird thing is I have never setup iCloud3 but I still have found this log:

Logger: homeassistant.config_entries
Source: helpers/entity_component.py:179 
First occurred: 22:52:00 (1 occurrences) 
Last logged: 22:52:00

Error setting up entry iCloud3 for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/config_entry.py", line 45, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 179, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

**Comment by gcobb321** [comment]
Delete t the iCloud3 integration and all files in custom_components/icloud3 directory. Restart HA 2 times. Reinstall iCloud3 beta 16b, restart HA and readd the integration

**Comment by DerDon1302** [comment]
> Delete t the iCloud3 integration and all files in custom_components/icloud3 directory. Restart HA 2 times. Reinstall iCloud3 beta 16b, restart HA and readd the integration

Sadly still the same 'unknown error'.

Here are the logs showing up after reinstalling and configuring my iCloud account:

2023-05-11 13:08:22.545 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration icloud3 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-11 13:12:13.519 WARNING (MainThread) [icloud3] iCloud3 - Migrating Configuration Parameters
2023-05-11 13:12:13.528 WARNING (MainThread) [icloud3] iCloud3 - Migration Complete
File "/config/custom_components/icloud3/config_flow.py", line 766, in async_step_menu
File "/config/custom_components/icloud3/config_flow.py", line 1979, in async_step_device_list
File "/config/custom_components/icloud3/config_flow.py", line 2523, in _build_device_form_selection_lists
File "/config/custom_components/icloud3/config_flow.py", line 2681, in _build_opt_iosapp_entity_list
File "/config/custom_components/icloud3/config_flow.py", line 2681, in <dictcomp>
File "/config/custom_components/icloud3/config_flow.py", line 766, in async_step_menu
File "/config/custom_components/icloud3/config_flow.py", line 1979, in async_step_device_list
File "/config/custom_components/icloud3/config_flow.py", line 2523, in _build_device_form_selection_lists
File "/config/custom_components/icloud3/config_flow.py", line 2681, in _build_opt_iosapp_entity_list
File "/config/custom_components/icloud3/config_flow.py", line 2681, in <dictcomp>
2023-05-11 13:14:02.293 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry iCloud3 for device_tracker
2023-05-11 13:14:02.326 ERROR (SyncWorker_2) [icloud3] 'PyiCloudService' object has no attribute '_webservices'
File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 1064, in create_FamilySharing_object
File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 1039, in _get_webservice_url
AttributeError: 'PyiCloudService' object has no attribute '_webservices'
2023-05-11 13:14:02.329 ERROR (SyncWorker_2) [icloud3] 'PyiCloudService' object has no attribute '_webservices'
File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 1090, in create_FindMyFriends_object
File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 1039, in _get_webservice_url
AttributeError: 'PyiCloudService' object has no attribute '_webservices'
File "/config/custom_components/icloud3/config_flow.py", line 766, in async_step_menu
File "/config/custom_components/icloud3/config_flow.py", line 1979, in async_step_device_list
File "/config/custom_components/icloud3/config_flow.py", line 2523, in _build_device_form_selection_lists
File "/config/custom_components/icloud3/config_flow.py", line 2681, in _build_opt_iosapp_entity_list
File "/config/custom_components/icloud3/config_flow.py", line 2681, in <dictcomp>
File "/config/custom_components/icloud3/config_flow.py", line 768, in async_step_menu
File "/config/custom_components/icloud3/config_flow.py", line 978, in async_step_change_device_order
File "/config/custom_components/icloud3/config_flow.py", line 3827, in form_schema
File "/config/custom_components/icloud3/config_flow.py", line 768, in async_step_menu
File "/config/custom_components/icloud3/config_flow.py", line 978, in async_step_change_device_order
File "/config/custom_components/icloud3/config_flow.py", line 3827, in form_schema
File "/config/custom_components/icloud3/config_flow.py", line 766, in async_step_menu
File "/config/custom_components/icloud3/config_flow.py", line 1979, in async_step_device_list
File "/config/custom_components/icloud3/config_flow.py", line 2523, in _build_device_form_selection_lists
File "/config/custom_components/icloud3/config_flow.py", line 2681, in _build_opt_iosapp_entity_list
File "/config/custom_components/icloud3/config_flow.py", line 2681, in <dictcomp>

**Comment by gcobb321** [comment]
It looks like the configuration info was migrated ok from the log file. I’m wondering since HA started with the old ‘platform: icloud3’ statement, it still thinks that is running and causing the error.

There have been some ha changes since I last ran through the migration.

Remove that and the other iCloud3 parameters from the HA configuration. Yank file, restart HA (maybe twice) and try again. I’m out so can not try it on my system.

————————
Gary Cobb

**Comment by gcobb321** [comment]
All of the error messages above have to do with Apple not supporting  the FmF a web interface any more. I have added additional checks in the interface program. Some I could test, others only partly.

Unzip the `pyicloud_ic3.zip` file below into the `icloud3/support` directory and restart HA.

Let me know if this works so I can put it in the next beta release or fix it.

[pyicloud_ic3.zip](https://github.com/gcobb321/icloud3_v3/files/11467657/pyicloud_ic3.zip)

**Comment by DerDon1302** [comment]
> All of the error messages above have to do with Apple not supporting the FmF a web interface any more. I have added additional checks in the interface program. Some I could test, others only partly.
> 
> Unzip the `pyicloud_ic3.zip` file below into the `icloud3/support` directory and restart HA.
> 
> Let me know if this works so I can put it in the next beta release or fix it.
> 
> [pyicloud_ic3.zip](https://github.com/gcobb321/icloud3_v3/files/11467657/pyicloud_ic3.zip)

Sadly after beta 16c I still get the same "unknown error" when trying to add a device with the configuration wizard. But now I get a different log file when I hit "select" on the add device category:

Logger: aiohttp.server
Source: util/__init__.py:47 
First occurred: 19:23:41 (3 occurrences) 
Last logged: 19:24:35

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 241, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/icloud3/config_flow.py", line 784, in async_step_menu
    return await self.async_step_device_list()
  File "/config/custom_components/icloud3/config_flow.py", line 1999, in async_step_device_list
    await self._build_device_form_selection_lists()
  File "/config/custom_components/icloud3/config_flow.py", line 2548, in _build_device_form_selection_lists
    self._build_opt_iosapp_entity_list()
  File "/config/custom_components/icloud3/config_flow.py", line 2706, in _build_opt_iosapp_entity_list
    {f"Search: {slugify(entity_attrs['original_name'])}":
  File "/config/custom_components/icloud3/config_flow.py", line 2706, in <dictcomp>
    {f"Search: {slugify(entity_attrs['original_name'])}":
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 47, in slugify
    slug = unicode_slug.slugify(text, separator=separator)
  File "/usr/local/lib/python3.10/site-packages/slugify/slugify.py", line 104, in slugify
    text = _unicode(text, 'utf-8', 'ignore')
TypeError: decoding to str: need a bytes-like object, int found

**Comment by gcobb321** [comment]
Unzip this into the icloud3 directory and restart HA

[config_flow.zip](https://github.com/gcobb321/icloud3_v3/files/11472883/config_flow.zip)

**Comment by DerDon1302** [comment]
That worked. Thank you very much for all the help!
