### ISSUE TITLE
Dictionary changed size during iteration

### ISSUE THREAD

**Issue by mobiledude** [gcobb321/icloud3_v3#133]
Got this error in my logs with 16c

Logger: icloud3
Source: core.py:1392
First occurred: 06:18:27 (1 occurrences)
Last logged: 06:18:27

dictionary changed size during iteration
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/start_ic3.py", line 1110, in create_Devices_object
    Device.write_ha_device_tracker_state()
  File "/config/custom_components/icloud3/device.py", line 1324, in write_ha_device_tracker_state
    self.DeviceTracker.write_ha_device_tracker_state()
  File "/config/custom_components/icloud3/device_tracker.py", line 518, in write_ha_device_tracker_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/config_entry.py", line 255, in state
    zone_state = zone.async_active_zone(
  File "/usr/src/homeassistant/homeassistant/components/zone/__init__.py", line 111, in async_active_zone
    for entity_id in sorted(hass.states.async_entity_ids(DOMAIN))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1392, in async_entity_ids
    return [
  File "/usr/src/homeassistant/homeassistant/core.py", line 1392, in <listcomp>
    return [
RuntimeError: dictionary changed size during iteration

**Comment by gcobb321** [comment]
Added an additional check to catch the error. Will be in next update
