### ISSUE TITLE
type object 'GlobalVariables' has no attribute 'iC3_debug_log_file_last_write_secs'

### ISSUE THREAD

**Issue by poudenes** [gcobb321/icloud3_v3#14]
Heym

With latest beta release I see this error every 5 minutes:

```
2022-12-25 12:05:00.292 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/icloud3/icloud3_main.py", line 209, in _polling_loop_5_sec_device
    self._main_5sec_loop_special_time_control()
  File "/config/custom_components/icloud3/icloud3_main.py", line 479, in _main_5sec_loop_special_time_control
    if (Gb.iC3_debug_log_file_last_write_secs > 0
AttributeError: type object 'GlobalVariables' has no attribute 'iC3_debug_log_file_last_write_secs'
```

**Comment by gcobb321** [comment]
Will fix in beta3a, probably tomorrow. Set Log Level to Info on the Configurator > Event Log screen to stop the error from occurring.

————————
Gary Cobb

**Comment by mobiledude** [comment]
![Screenshot 2022-12-27 om 07 56 35](https://user-images.githubusercontent.com/52012485/209625043-80e92660-cdec-453a-9e2a-e5f15abed6c0.jpg)
it remains when this is selected

**Comment by poudenes** [comment]
> Will fix in beta3a, probably tomorrow. Set Log Level to Info on the Configurator > Event Log screen to stop the error from occurring. ———————— Gary Cobb
> […](#)

The log leven is already on info...

**Comment by gcobb321** [comment]
I have fixed this in beta 4

**Comment by poudenes** [comment]
Changed log to RAW into HA log. Now the error is gone
