### ISSUE TITLE
Several errors in HA log

### ISSUE THREAD

**Issue by poudenes** [gcobb321/icloud3_v3#16]
Hey,

I remove always old files and unzip the new once.  With icloud3-beta4 I get this error message:
Checked configuration and restart iCloud3. Also restarted HA again get same errors.

```
2022-12-28 08:59:15.927 ERROR (SyncWorker_2) [icloud3] name 'log_info_msg' is not defined
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/iosapp_interface.py", line 128, in get_mobile_app_notifications
    notify_services = dict(services.__dict__)['_services']['notify']
KeyError: 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/iosapp_interface.py", line 103, in get_entity_registry_mobile_app_devices
    notify_iosapp_devicenames = get_mobile_app_notifications()
  File "/config/custom_components/icloud3/support/iosapp_interface.py", line 135, in get_mobile_app_notifications
    log_info_msg("iOS App Notify Service has not been set up yet. iCloud3 will retry later.")
NameError: name 'log_info_msg' is not defined
2022-12-28 08:59:15.936 ERROR (SyncWorker_2) [icloud3] name 'log_info_msg' is not defined
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/iosapp_interface.py", line 128, in get_mobile_app_notifications
    notify_services = dict(services.__dict__)['_services']['notify']
KeyError: 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/start_ic3_control.py", line 225, in stage_4_setup_tracking_methods
    start_ic3.setup_tracked_devices_for_iosapp()
  File "/config/custom_components/icloud3/support/start_ic3.py", line 1690, in setup_tracked_devices_for_iosapp
    setup_notify_service_name_for_iosapp_devices()
  File "/config/custom_components/icloud3/support/start_ic3.py", line 1721, in setup_notify_service_name_for_iosapp_devices
    notify_iosapp_devicenames = iosapp_interface.get_mobile_app_notifications()
  File "/config/custom_components/icloud3/support/iosapp_interface.py", line 135, in get_mobile_app_notifications
    log_info_msg("iOS App Notify Service has not been set up yet. iCloud3 will retry later.")
NameError: name 'log_info_msg' is not defined
2022-12-28 08:59:16.010 ERROR (SyncWorker_2) [icloud3] name 'log_info_msg' is not defined
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/iosapp_interface.py", line 128, in get_mobile_app_notifications
    notify_services = dict(services.__dict__)['_services']['notify']
KeyError: 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/iosapp_interface.py", line 103, in get_entity_registry_mobile_app_devices
    notify_iosapp_devicenames = get_mobile_app_notifications()
  File "/config/custom_components/icloud3/support/iosapp_interface.py", line 135, in get_mobile_app_notifications
    log_info_msg("iOS App Notify Service has not been set up yet. iCloud3 will retry later.")
NameError: name 'log_info_msg' is not defined
2022-12-28 08:59:16.018 ERROR (SyncWorker_2) [icloud3] name 'log_info_msg' is not defined
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/iosapp_interface.py", line 128, in get_mobile_app_notifications
    notify_services = dict(services.__dict__)['_services']['notify']
KeyError: 'notify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/start_ic3_control.py", line 225, in stage_4_setup_tracking_methods
    start_ic3.setup_tracked_devices_for_iosapp()
  File "/config/custom_components/icloud3/support/start_ic3.py", line 1690, in setup_tracked_devices_for_iosapp
    setup_notify_service_name_for_iosapp_devices()
  File "/config/custom_components/icloud3/support/start_ic3.py", line 1721, in setup_notify_service_name_for_iosapp_devices
    notify_iosapp_devicenames = iosapp_interface.get_mobile_app_notifications()
  File "/config/custom_components/icloud3/support/iosapp_interface.py", line 135, in get_mobile_app_notifications
    log_info_msg("iOS App Notify Service has not been set up yet. iCloud3 will retry later.")
NameError: name 'log_info_msg' is not defined
```

**Comment by gcobb321** [comment]
Beta 5 - 12/??/2022
~~~~~~~~~~~~~~~~~~~~
1.  Fixed a 'log_info_msg' not defined error message in the routine that identifies the notify 
    service  used for a device. This is just an informative message indicating HA has not set it 
    up yet.
