### ISSUE TITLE
Beta 19 another issue

### ISSUE THREAD

**Issue by criticallimit** [gcobb321/icloud3_v3#162]
This Fault is logged since I upgraded to Beta 19:

```


Logger: icloud3
Source: custom_components/icloud3/support/start_ic3.py:1877 
Integration: iCloud3 v3 (documentation, issues) 
First occurred: 10:25:08 (1 occurrences) 
Last logged: 10:25:08

list index out of range
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/start_ic3_control.py", line 286, in stage_5_configure_tracked_devices
    start_ic3.setup_trackable_devices()
  File "/config/custom_components/icloud3/support/start_ic3.py", line 1877, in setup_trackable_devices
    PairedDevices[0].PairedDevice = PairedDevices[1]
                                    ~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by criticallimit** [comment]
and when I restart the integration this is followed:

```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:187 
First occurred: 10:42:59 (1 occurrences) 
Last logged: 10:42:59

Error setting up entry iCloud3 for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/config_entry.py", line 45, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```

**Comment by gcobb321** [comment]
The first problem caused the other. 

There it’s probably a Watch paired with an untracked iPhone or Vice-versa that it’s causing the problem. I’ll update beta 19 tomorrow. 

If you want to fix it now, edit the _start_ic3.py_ in the _icloud3/support_ directory_:
Change lines 1877-1878

from:
```
         PairedDevices[0].PairedDevice = PairedDevices[1]
         PairedDevices[1].PairedDevice = PairedDevices[0]
```
          
to:
```
        try:
             PairedDevices[0].PairedDevice = PairedDevices[1]
             PairedDevices[1].PairedDevice = PairedDevices[0]
        except:
              pass
```

The `try` should line up underneath `PairedDevices`in line 1876.

**Comment by criticallimit** [comment]
start_ic3.py edited, fault is gone.

Thanx a lot
