### ISSUE TITLE
B19 - Async Setup Entry Error (URL)

### ISSUE THREAD

**Issue by MaxChlan** [gcobb321/icloud3_v3#165]
Hi all,

I just upgraded to B19, and received the following error on restart: 

2023-07-10 08:52:08.054 ERROR (MainThread) [icloud3] 
Traceback (most recent call last):
  File "/config/custom_components/icloud3/__init__.py", line 129, in async_setup_entry
    Gb.network_url    = network.get_url(hass)
                        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 200, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

I've tried backtracking to Main, as well as to 18.5 with no success in resolving this error. I have a suspicion that it's something on my side, but wanted to validate that someone else isn't running into this issue before I spend more time troubleshooting.

**Comment by MaxChlan** [comment]
Update: I was able to resolve this.
