### ISSUE TITLE
v3.0 rc3a: AttributeError: 'DeletedDeviceEntry' object has no attribute 'name'

### ISSUE THREAD

**Issue by Snuffy2** [gcobb321/icloud3_v3#183]
Seeing this on every HA boot from icloud3 Debug Log:
```
2023-08-20 15:40:57 [__init__....:0136]  son2, son2s_iphone:
										{'ic3_devicename': 'son2s_iphone', 'fname': 'son2', 'picture': 'None', 'evlog_display_order': 0, 'unique_id': '', 'device_type': 'iphone', 'inzone_interval': 120.0, 'tracking_mode': 'track', 'famshr_devicename': "son2's iPhone", 'famshr_device_id': 'AUfPhNVVaDN0td++R46k333FzQOELVeCIKsMddjlx0f/V+8dPl6tcsrsLzCAJ0GwWyNMkl9zJETFm6CQbNuQe32qdHJq8io4RAxiROrX0j0dQG4pny978Fob33oXguqCNhd6wQwu333PT1Oul783LbwyBAnctspuQFhHWAd9ivAIZLAnwa1K', 'raw_model': 'iPhone14,6', 'model': '', 'model_display_name': '', 'fmf_email': 'None', 'fmf_device_id': '', 'iosapp_device': 'son2s_iphone_app', 'track_from_base_zone': 'home', 'track_from_zones': ['home'], 'old_devicename': 'son2s_iphone'}
2023-08-20 15:40:57 [__init__....:0136]  
2023-08-20 15:40:57 [__init__....:0142]  Setting up iCloud3 3.0rc3a - Using Integration method
2023-08-20 15:41:16 [device_track:0204]  Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 189, in _get_dr_device_id_from_device_entry
    if device_entry.name in [DOMAIN, ICLOUD3, 'iCloud3 Integration']:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'DeletedDeviceEntry' object has no attribute 'name'
2023-08-20 15:41:16 [device_track:0204]  Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 189, in _get_dr_device_id_from_device_entry
    if device_entry.name in [DOMAIN, ICLOUD3, 'iCloud3 Integration']:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'DeletedDeviceEntry' object has no attribute 'name'
2023-08-20 15:41:16 [device_track:0204]  Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 189, in _get_dr_device_id_from_device_entry
    if device_entry.name in [DOMAIN, ICLOUD3, 'iCloud3 Integration']:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'DeletedDeviceEntry' object has no attribute 'name'
2023-08-20 15:41:16 [device_track:0264]  Device Tracker entity created: device_tracker.snuffy2s_iphone, #1
2023-08-20 15:41:17 [device_track:0264]  Device Tracker entity created: device_tracker.wifes_iphone, #2
2023-08-20 15:41:17 [device_track:0264]  Device Tracker entity created: device_tracker.son1s_iphone, #3
2023-08-20 15:41:17 [device_track:0264]  Device Tracker entity created: device_tracker.son2s_iphone, #4
2023-08-20 15:41:17 [device_track:0109]  Device Tracker Entities: 4
2023-08-20 15:41:18 [device_track:0204]  Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 189, in _get_dr_device_id_from_device_entry
    if device_entry.name in [DOMAIN, ICLOUD3, 'iCloud3 Integration']:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'DeletedDeviceEntry' object has no attribute 'name'
2023-08-20 15:41:18 [device_track:0204]  Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 189, in _get_dr_device_id_from_device_entry
    if device_entry.name in [DOMAIN, ICLOUD3, 'iCloud3 Integration']:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'DeletedDeviceEntry' object has no attribute 'name'
2023-08-20 15:41:18 [device_track:0204]  Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 189, in _get_dr_device_id_from_device_entry
    if device_entry.name in [DOMAIN, ICLOUD3, 'iCloud3 Integration']:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'DeletedDeviceEntry' object has no attribute 'name'
```

**Comment by gcobb321** [comment]
[device_tracker.zip](https://github.com/gcobb321/icloud3_v3/files/12389088/device_tracker.zip)

Unzip that into the icloud3 directory and restart ha

**Comment by Snuffy2** [comment]
Looking good. No longer seeing the error and the trackers appear to be updating.

**Comment by gcobb321** [comment]
Thanks. I just updated everything and have uploaded a prelease to the old iCloud3 repository.

**Comment by Snuffy2** [comment]
I won't be able to test again likely for a few days, but I just installed v3.0 rc3b which shows as pr1 in the ic3 logs.

The same errors as above are showing again.

```
2023-08-20 17:02:32.800 ERROR (MainThread) [icloud3] 'DeletedDeviceEntry' object has no attribute 'name'
Traceback (most recent call last):
File "/config/custom_components/icloud3/device_tracker.py", line 189, in _get_dr_device_id_from_device_entry
if device_entry.name in [DOMAIN, ICLOUD3, 'iCloud3 Integration']:
^^^^^^^^^^^^^^^^^
AttributeError: 'DeletedDeviceEntry' object has no attribute 'name'
```
