### ISSUE TITLE
Typo in iCloud_v3_beta5

### ISSUE THREAD

**Issue by poudenes** [gcobb321/icloud3_v3#20]
'/config/custom_components/icloud3/event_log_cad/ipad.png'

must be

'/config/custom_components/icloud3/event_log_card/ipad.png'

```
2022-12-29 09:16:46.224 ERROR (SyncWorker_7) [icloud3] [Errno 2] No such file or directory: '/config/custom_components/icloud3/event_log_cad/ipad.png'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/start_ic3.py", line 724, in _copy_image_files_to_www_directory
    shutil.copy(image_filename, www_evlog_directory)
  File "/usr/local/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/config/custom_components/icloud3/event_log_cad/ipad.png'
```

When change it manual and restart HA I have no errors at all anymore :)

**Comment by gcobb321** [comment]
it was suppose to be event-log-card, not event-log-cad...

Thanks, fixed in beta 6
