### ISSUE TITLE
"Unknown error occurred" when trying to edit devices

### ISSUE THREAD

**Issue by marceloaf** [gcobb321/icloud3_v3#30]
Hi Gary. I migrated from b7 to b8 and tried to edit devices. Got "unknown error occurred". No debug information is generated because of this action (click icloud3 devices)

![image](https://user-images.githubusercontent.com/11551691/212494241-8069bae3-27ec-4e6a-a644-c0fb7d33054a.png)

**Comment by gcobb321** [comment]
Just great. Are there any error messages in the HA home-assistant.log 
file? Like one dealing with HA has found a Blocking message and a 
routine should be run as part of the Executor Job or something like tht?

Gary Cobb


------ Original Message ------
From "marceloaf" ***@***.***>
To "gcobb321/icloud3_v3" ***@***.***>
Cc "Subscribed" ***@***.***>
Date 1/14/2023 3:19:47 PM
Subject [gcobb321/icloud3_v3] "Unknown error occurred" when trying to 
edit devices (Issue #30)

**Comment by marceloaf** [comment]
Here it is:

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/icloud3/config_flow.py:2150
Integration: iCloud3 Device Tracker (documentation, issues)
First occurred: 17:34:01 (1 occurrences)
Last logged: 17:34:01

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 241, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 286, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 374, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/icloud3/config_flow.py", line 609, in async_step_menu
    return await self.async_step_device_list()
  File "/config/custom_components/icloud3/config_flow.py", line 1559, in async_step_device_list
    self._build_device_form_selection_lists()
  File "/config/custom_components/icloud3/config_flow.py", line 2136, in _build_device_form_selection_lists
    self._build_opt_famshr_devices_list()
  File "/config/custom_components/icloud3/config_flow.py", line 2150, in _build_opt_famshr_devices_list
    devices_desc = start_ic3.get_famshr_devices(self.PyiCloud)
AttributeError: module 'custom_components.icloud3.support.start_ic3' has no attribute 'get_famshr_devices'

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by gcobb321** [comment]
It looks like I included the b7 version with some text code in one of 
the modules instead of the b8 version. Fixing no and will send you that 
module in a few minutes. I've pulled b8 from GitHub

Gary Cobb


------ Original Message ------
From "marceloaf" ***@***.***>
To "gcobb321/icloud3_v3" ***@***.***>
Cc "Gary Cobb" ***@***.***>; "Comment" 
***@***.***>
Date 1/14/2023 3:35:59 PM
Subject Re: [gcobb321/icloud3_v3] "Unknown error occurred" when trying 
to edit devices (Issue #30)

**Comment by gcobb321** [comment]
I had a b7 version of config_flow.py, the module that handles the 
configuration update. Coyp the attached file into the 
custom_components/icloud3 directory, replacing the one that is there. 
Restart HA and give it another try.

Gary


------ Original Message ------
From "marceloaf" ***@***.***>
To "gcobb321/icloud3_v3" ***@***.***>
Cc "Gary Cobb" ***@***.***>; "Comment" 
***@***.***>
Date 1/14/2023 3:35:59 PM
Subject Re: [gcobb321/icloud3_v3] "Unknown error occurred" when trying 
to edit devices (Issue #30)

**Comment by marceloaf** [comment]
Where is the config_flow.py? It didn't come attached...

**Comment by gcobb321** [comment]
[config_flow.zip](https://github.com/gcobb321/icloud3_v3/files/10418827/config_flow.zip)

I thought I was sending via an email instead of a github file.

**Comment by marceloaf** [comment]
config_flow.py didn’t come attached…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by gcobb321** [comment]
Just attached to the GitHub issue you opened

Gary Cobb

**Comment by marceloaf** [comment]
Worked fine! Tks 👍 

![image](https://user-images.githubusercontent.com/11551691/212496836-71984833-b50a-46bd-af90-552d9154acf0.png)

**Comment by derekoharrow** [comment]
Beta 8a seems to have fixed this - thanks!

**Comment by gcobb321** [comment]
Fixed in Beta 8a
