### ISSUE TITLE
Apple ID get's locked every 1-3 days and ic3 often fails at startup even when account is not locked

### ISSUE THREAD

**Issue by Snuffy2** [gcobb321/icloud3_v3#317]
I'm reporting these together as I suspect they are related. I have several apple devices linked to my apple ID but I think that ic3 is the only non-apple thing that directly uses my apple credentials. I have 5 trackers setup in ic3, myself and 4 family members all shared via Family Sharing.  For about the last month, my Apple ID has been getting locked every 1-3 days.

I'll notice that icloud3 isn't updating and notice in the ic3 logs that there are errors. I'll then open icloud.com (not in Safari) and after logging in get notified my account is locked. I'll follow the steps to unlock my account and then get an email from Apple confirming that my account is now unlocked. Additionally, I can then go to icloud.com and browse my account sucessfully.

Once unlocked, I'll then go to ic3 and select Restart icloud3. Sometimes it restarts fine and all 5 trackers come up. However ~50% of the time only my tracker comes up and the rest show yellow triangles. The debug log for starting up where it only finds my device is here:
[icloud3-0_bad_init.log](https://github.com/user-attachments/files/16317212/icloud3-0_bad_init.log)

Additionally, since this frequent Apple ID locking has started, when I restart ic3, it is about 50/50 whether it will startup correctly or only have my tracker working with the rest having yellow triangles. This happens when my account isn't currently locked and that I haven't had to unlock it in the last several hours to days.

Any thoughts on this? Both the frequent Applid ID locking and the ic3 failed startup?

**Comment by Snuffy2** [comment]
<img width="318" alt="2024-07-19_17-53-24" src="https://github.com/user-attachments/assets/f4cdc89a-e8e9-4364-9598-5bf0ea5e34a7">

**Comment by garyak** [comment]
I've encountered a similar situation. Unfortunately, I haven't been able to get IC3 to accept the new AppleID credentials.

**Comment by gcobb321** [comment]
@garyak 
If iCloud3 won’t save a username/password change, on the _Configure Settings > Apple Acct screen_, try selecting the ‘log out’ option and submit  then save and submit to clear them from the configuration.  Then go back and enter the new ones, log in and submit, then save and submit.

**Comment by gcobb321** [comment]
@Snuffy2 
When iCloud3 first logs into the Apple Account, Apple returns the devices in the Family Share list. That is used to build the internal tables and t tie everything together. Sometimes it doesn’t return all of them. iCloud3 checks for this and requests for them again. Most of the time it gets them. Sometimes there is an issue with a watch not being returned when it has been charging on the counter overnight or has not been worn for several days Anna Apple seems to loose track of it. Check the FindMe app and see it the device that doesn’t load shows as available before you restart. An older version of iCloud3 has a problem with the retry where it thought it was asking for a data refresh but it really wasn’t and was just looking as the same data 10-times before failing. 

You have Log level debug.  You really want ’rawdata’ . Rawdata dumps the data request and what was returned from Apple to the log file. It shows the devices that are returned when iCloud3 starts and all the raw Location data when it is running. Turn it on in _Configure Settings > Page 2 > Format Parameters_ screen so it stays on overnight. Selecting it from the _Event Log > Actions > xx_ will turn it off at midnight. Then let’s see what Apple is returning. There is a ‘locked: True’ field in the data that might show what was going on when it was set. 

3-days of log files are kept and they e at midnight. -0 is today, -1 is yesterday and-2 is the day before. If it takes several days to show to, you might need to rename them each day so they are not lost. If this seems to happen more on one device, put that device name in the filter field on the _Configure Settings > Page 2 > Format Parameters_ screen. That will limit the raw data to only that device and I don’t have to go through a lot of hay to find the needle.

**Comment by garyak** [comment]
@gcobb321 I reloaded fresh code as I was getting new waze errors. All errors are now gone from the event log, but still not connected to icloud after updating credentials. Logs in OK, but doesn't appear to save as I go back to enter the verification code. Request new verification from the Event Log pull-down isn't working for me now. Also, the configure button on the Event Log just circles back instead of initiating the config routine.

**Comment by gcobb321** [comment]
@garyak Can you go to configure via Settings > Devices Anna Services > iCloud3 > Configure?
Check the iCloud3 configuration file in _.storage/icloud3/configuration_ and see if it is trashed. It does keep a backup of itself in case of errors. Look at the username and password fields. Clear them to remove the old credentials. That’s what the log out does.

**Comment by garyak** [comment]
Yes. Can access the configuration screens from devices and services. Configuration file at .storage/icloud3 shows null values for user credentials.

**Comment by gcobb321** [comment]
It sounds like HA may have created duplicate sensor entities with the _2 suffix. And maybe the dev trkr entities too. It did that to me last night with my iPad. The mobile app has 4 of them. You may have to go to the devices and settings and rename the entities or go into the iCloud3 _Configure Settings >_  and select them again.

**Comment by smarthomefamilyverrips** [comment]
> It sounds like HA may have created duplicate sensor entities with the _2 suffix. And maybe the dev trkr entities too. It did that to me last night with my iPad. The mobile app has 4 of them. You may have to go to the devices and settings and rename the entities or go into the iCloud3 _Configure Settings >_ and select them again.

@gcobb321 after I got prompted to re-authenticate tonight I noticed few hours later after I did re-authentificated and reloaded the integration all sensors created by the Icloud V3 integration got duplicated and got the _2 suffix.

![Screenshot_20240722_013651_Home Assistant](https://github.com/user-attachments/assets/05552d1e-2cc1-4741-9201-e4a14052a2d6)

The problem now is I can not rename them by remove the _2 suffix because those entity names still exist, if I try to delete them trying to use th clokwheel within the entity window I can not because it show me that the entity have no unique ID.

![Screenshot_20240722_014402_Home Assistant](https://github.com/user-attachments/assets/2df4134d-fff9-4a6e-9b30-9b77f164810a)

You have any suggestion how I can remove these "unavailable" entities?

**Comment by garyak** [comment]
You can disable unwanted entities.

**Comment by smarthomefamilyverrips** [comment]
> You can disable unwanted entities.

@garyak No I can not because I can not enter the entity because it not have a unique-id, and every reload I do creates a duplicate of the sensors with a next in line number suffix

**Comment by garyak** [comment]
@smarthomefamilyverrips  I haven't run into your problem before. If available, you could restore a recent backup. I usually have gotten duplicate entries with numeric (-2) additions when I reinstall over the top of a previous installation. I now delete the previous integration and restart HA before installing a new instance of IC3. The difficult option is to stop HA core and edit the core.entity_registry file to remove, I reccomend you backup the original file before you edit.

**Comment by gcobb321** [comment]
@smarthomefamilyverrips This problem should really be in its own issue since it does not relate to the title of the problem even though it is similar to the one GaryK was having.  

To remove the _unavailable_ entities, click the check box to select all entities and then select _remove_..HA will only remove the ones that are unstable and leave the rest. Then restart HA and rename the ones wits the _2 to their correct name without the _2

**Comment by smarthomefamilyverrips** [comment]
> @smarthomefamilyverrips This problem should really be in its own issue since it does not relate to the title of the problem even though it is similar to the one GaryK was having.
> 
> To remove the _unavailable_ entities, click the check box to select all entities and then select _remove_..HA will only remove the ones that are unstable and leave the rest. Then restart HA and rename the ones wits the _2 to their correct name without the _2

@gcobb321 what checkbox you mean?

**Comment by gcobb321** [comment]
@smarthomefamilyverrips settings >devices and services >settings >entities. Then click the  icon to the right of the filters icon  on the top row display the check boxes next to the entities. Check the one on the top row to select everything

**Comment by gcobb321** [comment]
@smarthomefamilyverrips You may have to disable iCloud3 and restart HA 2 times. Then try again to clean out everything. Then reenable iCloud3 and restart HA again. I would do a backup first in case of problems

**Comment by smarthomefamilyverrips** [comment]
> @smarthomefamilyverrips You may have to disable iCloud3 and restart HA 2 times. Then try again to clean out everything. Then reenable iCloud3 and restart HA again. I would do a backup first in case of problems

@gcobb321 I will try this then and let you know if worked

**Comment by smarthomefamilyverrips** [comment]
@gcobb321 instead of disable the integration I did power cycle my HA Blue and that did remove all duplicate entities, Only now I am unable to create a new battery sensor, If i select it within sensor section by checking the checkbox and click submit it gives me message "unknow error occured"and the blow is in the HA logs

Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
First occurred: 17:25:57 (1 occurrences)
Last logged: 17:25:57

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 285, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 415, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 518, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/icloud3/config_flow.py", line 1542, in async_step_sensors
    if self.common_form_handler(user_input, action_item, errors):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/icloud3/config_flow.py", line 1184, in common_form_handler
    self._remove_and_create_sensors(user_input)
  File "/config/custom_components/icloud3/config_flow.py", line 3618, in _remove_and_create_sensors
    self._create_sensor_entity(devicename, conf_device, new_sensors_list)
  File "/config/custom_components/icloud3/config_flow.py", line 3866, in _create_sensor_entity
    ic3_sensor._setup_recorder_exclude_sensor_filter(NewSensors)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'custom_components.icloud3.sensor' has no attribute '_setup_recorder_exclude_sensor_filter'

**Comment by gcobb321** [comment]
@smarthomefamilyverrips That is an iCloud3 bug. That code should have been removed in v3.0.5.5 that fixed the HA recorder issue that I missed. I'm working on that module for another issue and will post it here when it is ready.

**Comment by smarthomefamilyverrips** [comment]
> @smarthomefamilyverrips That is an iCloud3 bug. That code should have been removed in v3.0.5.5 that fixed the HA recorder issue that I missed. I'm working on that module for another issue and will post it here when it is ready.

@gcobb321 Ok I understand, but how I am able to add battery sensors now then as it not let me from the sensor configuration?

**Comment by gcobb321** [comment]
@smarthomefamilyverrips It may have been added. The last thing that was being done was generating the error msg after it had been created. Check to see if it exists. If not, you will have to wait for the update.

**Comment by smarthomefamilyverrips** [comment]
> @smarthomefamilyverrips It may have been added. The last thing that was being done was generating the error msg after it had been created. Check to see if it exists. If not, you will have to wait for the update.

@gcobb321 If I select the battery sensor by checking the checkbox and click submit indeed the battery sensors get created even while I just stay on the sensor configuration window instead of going back to previous window after clcking submit and still get the error message..... only the battery checkbox afterwards still is blank if I check and when I restart HA it makes the battery sensors become unavailable..... so I geuss I need to wait for update as you suggested, ant ETA on this, I alsocan try a beta if it helps you to see if solves this sensor select issue.

**Comment by smarthomefamilyverrips** [comment]
@gcobb321 if I use that I get "failed to setup, import error" and integration not starts

following in logs

Logger: homeassistant.config_entries
Source: config_entries.py:555
First occurred: 19:45:08 (1 occurrences)
Last logged: 19:45:08

Error importing platform config_flow from integration icloud3 to set up icloud3 configuration entry: cannot import name 'get_file_list' from 'custom_components.icloud3.helpers.common' (/config/custom_components/icloud3/helpers/common.py)

AND

Logger: homeassistant.util.loop
Source: util/loop.py:77
First occurred: 19:45:08 (1 occurrences)
Last logged: 19:45:08

Detected blocking call to import_module with args ('custom_components.icloud3.config_flow',) in /usr/src/homeassistant/homeassistant/loader.py, line 1296: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 734, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 553, in async_setup await integration.async_get_platform("config_flow") File "/usr/src/homeassistant/homeassistant/loader.py", line 1100, in async_get_platform platforms = await self.async_get_platforms((platform_name,)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1165, in async_get_platforms platforms.update(self._load_platforms(platform_names)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in _load_platforms platform_name: self._load_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform cache[full_name] = self._import_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform return importlib.import_module(f"{self.pkg_path}.{platform_name}")

**Comment by smarthomefamilyverrips** [comment]
@gcobb321 if I replace the configuration file in .storage/icloud3 with a configuration file of a back-up made this morning before I did uncheck the battery sensor in the sensor configuration it will not check again the battery sensor and not make it unavailable anymore when I restart HA?

This is my configuration file now:

{
  "profile": {
    "version": 1,
    "ic3_version": "3.0.5.5",
    "version_install_date": "2024-07-19 14:25:47",
    "config_update_date": "2024-07-22 16:53:50",
    "event_log_card_directory": "www/custom_cards",
    "event_log_card_program": "icloud3-event-log-card.js",
    "event_log_btnconfig_url": "",
    "event_log_version": "3.0.17",
    "event_log_version_running": "",
    "picture_www_dirs": [
      "www",
      "www/xplora_watch",
      "www/xplora_watch/emojis",
      "www/community",
      "www/community/weather-chart-card",
      "www/community/lovelace-mushroom",
      "www/community/lovelace-fan-xiaomi",
      "www/community/lovelace-hourly-weather",
      "www/community/button-card",
      "www/community/clock-weather-card",
      "www/community/platinum-weather-card",
      "www/community/simple-thermostat",
      "www/community/alarmo-card",
      "www/community/lovelace-digital-clock",
      "www/community/mini-media-player",
      "www/community/simple-clock-card",
      "www/community/mini-graph-card",
      "www/voice",
      "www/custom_cards",
      "www/image",
      "www/video",
      "www/video/thumb"
    ]
  },
  "data": {
    "tracking": {
      "username": "sesamstraat26@hotmail.com",
      "password": "*******************",
      "encode_password": true,
      "icloud_server_endpoint_suffix": "",
      "setup_icloud_session_early": true,
      "data_source": "famshr,mobapp",
      "devices": [
        {
          "ic3_devicename": "lory_iphone_new",
          "fname": "Lory Iphone New",
          "picture": "www/custom_cards/loredana.jpg",
          "evlog_display_order": 0,
          "unique_id": "",
          "device_type": "iphone",
          "inzone_interval": 5.0,
          "tracking_mode": "track",
          "famshr_devicename": "iPhone Lory",
          "famshr_device_id": "AXmZIYMW1z2oyH/o/xAquqcJEAfUY+9R8TFkpcneZ8FU4Di1MAiOAobdLL2IaZNRb21XEC7oUP+Ukw==",
          "raw_model": "iPhone15,2",
          "model": "iPhone",
          "model_display_name": "iPhone 14 Pro",
          "fmf_email": "None",
          "fmf_device_id": "",
          "track_from_base_zone": "home",
          "track_from_zones": [
            "home"
          ],
          "old_devicename": "lory_iphone_new",
          "log_zones": [
            "none"
          ],
          "fixed_interval": 0.0,
          "mobile_app_device": "iphone_lory"
        }
      ]
    },
    "general": {
      "log_level": "info",
      "unit_of_measurement": "km",
      "time_format": "24-hour",
      "display_zone_format": "fname",
      "max_interval": 240.0,
      "offline_interval": 20,
      "exit_zone_interval": 0.5,
      "old_location_threshold": 3.0,
      "old_location_adjustment": 0,
      "gps_accuracy_threshold": 40.0,
      "display_gps_lat_long": true,
      "travel_time_factor": 0.66,
      "tfz_tracking_max_distance": 8,
      "passthru_zone_time": 0,
      "track_from_base_zone": "home",
      "track_from_home_zone": false,
      "center_in_zone": false,
      "discard_poor_gps_inzone": false,
      "distance_between_devices": true,
      "inzone_intervals": {
        "iphone": 5.0,
        "ipad": 120.0,
        "watch": 15.0,
        "airpods": 15.0,
        "other": 120.0,
        "no_mobapp": 15.0
      },
      "waze_used": true,
      "waze_region": "row",
      "waze_min_distance": 1.0,
      "waze_max_distance": 1000,
      "waze_realtime": true,
      "waze_history_database_used": true,
      "waze_history_max_distance": 20,
      "waze_history_track_direction": "north_south",
      "stat_zone_fname": "StatZon#",
      "stat_zone_still_time": 0,
      "stat_zone_inzone_interval": 30.0,
      "stat_zone_base_latitude": 1,
      "stat_zone_base_longitude": 0,
      "display_text_as": [
        "#1",
        "#2",
        "#3",
        "#4",
        "#5",
        "#6",
        "#7",
        "#8",
        "#9",
        "#10"
      ],
      "device_tracker_state_source": "ic3_fname",
      "track_from_base_zone_used": false,
      "away_time_zone_1_offset": 0,
      "away_time_zone_1_devices": [
        "none"
      ],
      "away_time_zone_2_offset": 0,
      "away_time_zone_2_devices": [
        "none"
      ],
      "mobapp_alive_interval": 30.0,
      "log_level_devices": [
        "all"
      ]
    },
    "sensors": {
      "monitored_devices": [],
      "device": [],
      "tracking_update": [
        "last_located",
        "last_update",
        "next_update"
      ],
      "tracking_time": [
        "travel_time",
        "arrival_time"
      ],
      "tracking_distance": [
        "home_distance"
      ],
      "track_from_zones": [
        "tfz_zone_info",
        "tfz_travel_time",
        "tfz_arrival_time"
      ],
      "tracking_other": [
        "trigger"
      ],
      "zone": [],
      "other": [],
      "excluded_sensors": [
        "None"
      ]
    }
  }
}

And this is my Backed-Up configuration file

{
  "profile": {
    "version": 1,
    "ic3_version": "3.0.5.5",
    "version_install_date": "2024-07-19 14:25:47",
    "config_update_date": "2024-07-19 14:25:47",
    "event_log_card_directory": "www/custom_cards",
    "event_log_card_program": "icloud3-event-log-card.js",
    "event_log_btnconfig_url": "",
    "event_log_version": "3.0.17",
    "event_log_version_running": "",
    "picture_www_dirs": [
      "www",
      "www/xplora_watch",
      "www/xplora_watch/emojis",
      "www/community",
      "www/community/weather-chart-card",
      "www/community/lovelace-mushroom",
      "www/community/lovelace-fan-xiaomi",
      "www/community/lovelace-hourly-weather",
      "www/community/button-card",
      "www/community/clock-weather-card",
      "www/community/platinum-weather-card",
      "www/community/simple-thermostat",
      "www/community/alarmo-card",
      "www/community/lovelace-digital-clock",
      "www/community/mini-media-player",
      "www/community/simple-clock-card",
      "www/community/mini-graph-card",
      "www/voice",
      "www/custom_cards",
      "www/image",
      "www/video",
      "www/video/thumb"
    ]
  },
  "data": {
    "tracking": {
      "username": "sesamstraat26@hotmail.com",
      "password": "*******************",
      "encode_password": true,
      "icloud_server_endpoint_suffix": "",
      "setup_icloud_session_early": true,
      "data_source": "famshr,mobapp",
      "devices": [
        {
          "ic3_devicename": "lory_iphone_new",
          "fname": "Lory Iphone New",
          "picture": "www/custom_cards/loredana.jpg",
          "evlog_display_order": 0,
          "unique_id": "",
          "device_type": "iphone",
          "inzone_interval": 5.0,
          "tracking_mode": "track",
          "famshr_devicename": "iPhone Lory",
          "famshr_device_id": "AXmZIYMW1z2oyH/o/xAquqcJEAfUY+9R8TFkpcneZ8FU4Di1MAiOAobdLL2IaZNRb21XEC7oUP+Ukw==",
          "raw_model": "iPhone15,2",
          "model": "iPhone",
          "model_display_name": "iPhone 14 Pro",
          "fmf_email": "None",
          "fmf_device_id": "",
          "track_from_base_zone": "home",
          "track_from_zones": [
            "home"
          ],
          "old_devicename": "lory_iphone_new",
          "log_zones": [
            "none"
          ],
          "fixed_interval": 0.0,
          "mobile_app_device": "iphone_lory"
        }
      ]
    },
    "general": {
      "log_level": "info",
      "unit_of_measurement": "km",
      "time_format": "24-hour",
      "display_zone_format": "fname",
      "max_interval": 240.0,
      "offline_interval": 20,
      "exit_zone_interval": 0.5,
      "old_location_threshold": 3.0,
      "old_location_adjustment": 0,
      "gps_accuracy_threshold": 40.0,
      "display_gps_lat_long": true,
      "travel_time_factor": 0.66,
      "tfz_tracking_max_distance": 8,
      "passthru_zone_time": 0,
      "track_from_base_zone": "home",
      "track_from_home_zone": false,
      "center_in_zone": false,
      "discard_poor_gps_inzone": false,
      "distance_between_devices": true,
      "inzone_intervals": {
        "iphone": 5.0,
        "ipad": 120.0,
        "watch": 15.0,
        "airpods": 15.0,
        "other": 120.0,
        "no_mobapp": 15.0
      },
      "waze_used": true,
      "waze_region": "row",
      "waze_min_distance": 1.0,
      "waze_max_distance": 1000,
      "waze_realtime": true,
      "waze_history_database_used": true,
      "waze_history_max_distance": 20,
      "waze_history_track_direction": "north_south",
      "stat_zone_fname": "StatZon#",
      "stat_zone_still_time": 0,
      "stat_zone_inzone_interval": 30.0,
      "stat_zone_base_latitude": 1,
      "stat_zone_base_longitude": 0,
      "display_text_as": [
        "#1",
        "#2",
        "#3",
        "#4",
        "#5",
        "#6",
        "#7",
        "#8",
        "#9",
        "#10"
      ],
      "device_tracker_state_source": "ic3_fname",
      "track_from_base_zone_used": false,
      "away_time_zone_1_offset": 0,
      "away_time_zone_1_devices": [
        "none"
      ],
      "away_time_zone_2_offset": 0,
      "away_time_zone_2_devices": [
        "none"
      ],
      "mobapp_alive_interval": 30.0,
      "log_level_devices": [
        "all"
      ]
    },
    "sensors": {
      "monitored_devices": [],
      "device": [
        "battery"
      ],
      "tracking_update": [
        "last_located",
        "last_update",
        "next_update"
      ],
      "tracking_time": [
        "travel_time",
        "arrival_time"
      ],
      "tracking_distance": [
        "home_distance"
      ],
      "track_from_zones": [
        "tfz_zone_info",
        "tfz_travel_time",
        "tfz_arrival_time"
      ],
      "tracking_other": [
        "trigger"
      ],
      "zone": [],
      "other": [],
      "excluded_sensors": [
        "None"
      ]
    }
  }
}

**Comment by FrancoLoco** [comment]
my iCloud v3 also stopped working and I can't get it to log in again or anything..

**Comment by JtwoA** [comment]
> my iCloud v3 also stopped working and I can't get it to log in again or anything..

This is pretty vague.  

- Was it working previously?
- If yes, what changed?  (Did you update iC3, did you update HA?)
- What version are you on?
- What do the logs show?  (HA and iC3)

**Comment by FrancoLoco** [comment]
I was just able to make it work again, turns out my icloud account got locked (I don't know why) and I could unlock it by going on https://www.icloud.com/

**Comment by kurim** [comment]
This issue now happens again to me.
One suggetion, if login failed ones it should not hammer login so often to avoid account block.

**Comment by gcobb321** [comment]
The difficulty is figuring out what is causing this is it has never have happened to me and I have never seen any Log records that show the Apple account events from before it was locked to when it was locked. 

I would appreciate it if someone whose account locked several times would do this:
1. Go to the _Configure Settings > Page 2 > Format Parameters_ screen and set _log level_ to ‘rawdata‘. Also select the Apple account’s owner in the _Filter_ . This will limit the data being dumped to the log file to only the owners device instead of dumping the records for all devices being tracked. 
2. Let it run this way until the account is locked. 
3. When it happens, send the iCloud3 log files (icloud3-0.log, icloud3-1.log and icloud3-2.log) to geekstergary@gmail.com. The files will be big so you might want to zip them. If you zip them, you might have to change the file extension to something else (icloud3-logs.zip.data) to get around gmails filters.

**Comment by gcobb321** [comment]
Closing due to no activity and the release of iCloud3 v3.1.5
