### ISSUE TITLE
Findy my phone not executable

### ISSUE THREAD

**Issue by gekberlin** [gcobb321/icloud3_v3#35]
If i try to use the service find my phone from the lovelace card, the service is not running because of:"'PyiCloud_FamilySharing' object is not callable". If I set up an script like given in the docs the same error occurs.

**Comment by gcobb321** [comment]
I just tried it with Beta 8 and my phone chimed with the alert sound. What version are you running?

**Comment by gekberlin** [comment]
unfortatenely even with the newest beta (v3.0.0.b8b) the error is still there.
I copy'n' paste the code of the HA-log:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/icloud3/support/pyicloud_ic3.py:935
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 11:37:39 (2 occurrences)
Last logged: 11:37:59

[139976019275456] 'PyiCloud_FamilySharing' object is not callable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1798, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/icloud3/support/service_handler.py", line 116, in process_find_iphone_alert_service_request
    find_iphone_alert_service_handler(devicename)
  File "/config/custom_components/icloud3/support/service_handler.py", line 273, in find_iphone_alert_service_handler
    Gb.PyiCloud.play_sound(device_id)
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 935, in play_sound
    data = self.FamilySharing(service_root, self.Session, self.params, self.with_family,
TypeError: 'PyiCloud_FamilySharing' object is not callable`
```

**Comment by gcobb321** [comment]
I just uploaded Beta 9. Reopen this issue if you are still having problems after installing and using it.

Gary

**Comment by gekberlin** [comment]
Unfortunately the problem still exist, even with the newest beta. Any höhe further suggestions?

**Comment by gcobb321** [comment]
Is it generating an error message in the home-assistant.log file? 
Can you turn on debug logging (Configurator > Event Log Parameters > Log Level > Debug). 
Restart iCloud3 (Actions ? Restart iCloud3). 
Then try it and send/config/icloud3-debug.log file to geekstergary@gmail.com so I can see what is going on. 
It works on my system for FamShr devices (there is no support for this on FmF only devices or iOS App only devices)..

Maybe the debul.log file will show me the error you are having.

**Comment by denac** [comment]
I am getting the same errors as well

**Comment by gcobb321** [comment]
@denac  @gekberlin 
Are you both getting the same error message posted above in the home-assistant.log file?
W will you copy and posted the actual error message?
Can you post the beta version number (rather than ‘The latest’). It will help me look at the correct line number in the correct module? 

It’s the device you are locating using the FamShr tracking method or Find-my-friends?
T the icloud-debug.log file will help me see what is going on?
I’ll dig into it again but it was working for me?

The banks

**Comment by denac** [comment]
Version icloud3-beta-9
Using FamShr
Error Message:

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/icloud3/support/pyicloud_ic3.py:931
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 3:30:18 AM (1 occurrences)
Last logged: 3:30:18 AM

[546972725984] 'PyiCloud_FamilySharing' object is not callable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1798, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/icloud3/support/service_handler.py", line 113, in process_find_iphone_alert_service_request
    find_iphone_alert_service_handler(devicename)
  File "/config/custom_components/icloud3/support/service_handler.py", line 267, in find_iphone_alert_service_handler
    Gb.PyiCloud.play_sound(device_id)
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 931, in play_sound
    data = self.FamilySharing(service_root, self.Session, self.params, self.with_family,
TypeError: 'PyiCloud_FamilySharing' object is not callable

**Comment by kingy444** [comment]
i too had the issue on beta9 - I did some digging and found how to fix it.

but also just downloaded ic3-beta-11p1 and the issue is resolved there

@gcobb321  any chance you could get the beta versioning in the hacs manifest so we get notifications of the new releases via HACS ?

i think this issue could probably be closed

**Comment by gekberlin** [comment]
Yes, with beta 11 this issue is also fixed for me and the find my iPhone commands are executable again. 
Thanks!
