### ISSUE TITLE
iCloud3 v3.1 Dev ➤ Questions & Answers

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3_v3#350]
**Post any questions you have to this issue. Create a new issue if you are having problems.**

**Comment by NR3Y** [comment]
Gary,
With the release of v3.1, did the update require further operations? I just updated mine (on my MacOS HA browser), and I see the following as the 'Apple ID'. Tried to use it, but didn't get authentication code.

<img width="604" alt="Screenshot 2024-11-04 at 3 09 44 PM" src="https://github.com/user-attachments/assets/e6303764-928b-4203-b950-180956ecece8">

**Comment by Darkwulf183** [comment]
Me the same. I tested it today morning...

**Comment by asinwang** [comment]
APPLE ACCOUNT iCLOUD DEVICE - Apple iCloud device providing location data
🍎 ~~~~ xxxxx, Apple Account #1 of 1 ~~~~ 0 of 0 Tracked ~~~~

there  0 of 0 Tracked   , can't Tracked anything

**Comment by wormvortex** [comment]
Mine is showingg 0 out of 7 devices being tracked with no way of adding them.
<img width="296" alt="Screenshot 2024-11-05 at 14 56 29" src="https://github.com/user-attachments/assets/d12b67a0-cf22-47ef-b067-1edaaf1248ae">
<img width="600" alt="Screenshot 2024-11-05 at 14 56 43" src="https://github.com/user-attachments/assets/ffb09c65-256a-46d4-9661-4386b4f98a20">
<img width="600" alt="Screenshot 2024-11-05 at 14 56 48" src="https://github.com/user-attachments/assets/7093f0b1-525a-4012-8304-4c6544f98f6c">

**Comment by gcobb321** [comment]
@wormvortex 
See iCloud3 docs [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/3.2-installing-and-configuring?id=step-31-icloud-account-amp-mobile-app-screen) for adding devices

**Comment by NR3Y** [comment]
Gary, so I'm a little confused. My v3.1 Event Log does indeed show issues...but when I go to the integration and look at the entities, they're showing actual data (which they weren't before v3.1).

![Screenshot 2024-11-05 at 9 58 49 AM](https://github.com/user-attachments/assets/858bc23e-9cd7-44a9-8177-07cd159dc665)



<img width="486" alt="Screenshot 2024-11-05 at 9 47 51 AM" src="https://github.com/user-attachments/assets/703a97b1-951f-49a1-8948-d5654a471ae9">

**Comment by wormvortex** [comment]
> @wormvortex 
> 
> See iCloud3 docs [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/3.2-installing-and-configuring?id=step-31-icloud-account-amp-mobile-app-screen) for adding devices

I've looked in all the options and I don't have a 

"iCloud Account & Mobile App screen"

Has it changed in the new version.

**Comment by Darkwulf183** [comment]
I have exact the same event log like @NR3Y. No operations are capabble. I have 13 Automations on mine and my Wifes Iphone and will not experiment to much.

**Comment by NR3Y** [comment]
So, has anyone tried deleting the integration, rebooting/restart HA, then reinstalling it from HACS? I'm wondering whether a fresh install would 'clear' out the issues?

(For https://github.com/Darkwulf183 issue, you probably would need to delete the automation, they'd just be there ready for when you reinstall iCloud3 again.)

**Comment by gcobb321** [comment]
@NR3Y

**Comment by asinwang** [comment]
> @asinwang @Darkwulf183 @NR3Y The Apple account should be refreshed when iCloud3 starts to load the devices. Yours says 0 of 0 devices tracked, indicating that refresh did not happen. I am looking into that. Try doing an Event Log > Actions >, Locate all Devices with iCloud or Restart iCloud3 and look at Stage 3 & 4 to see if a refresh was done and the devices in your account are available.

This problem occurred on the second account I added. After the upgrade was completed, there was no problem with the original account. In addition, I created a new environment and tested it without success.

**Comment by t077584** [comment]
I managed to have the devices installed and it seems to work now, but I had to do a restart after each change (removing account and devices -> restart. Adding one device -> restart. Add the next one -> restart aso.) BUT, in the event log header bar, IC3Zone, Interval, Travel and Distance are empty. The only zone that is shown is the one of MobileApp. However, looking at the details of the exported event log, all of the above is updated and available (IC3, Intervl, TrvTime, Dist, Arrival etc). That said, it's probably only cosmetics. 

However, Waze seems to have sporadically issues:
Waze Connection Error, Region-ROW > No data returned. The route distance will be calculated, Travel Time is not available.

I won't log an issue, given Gary is working already on a bugfix release.

**Comment by gcobb321** [comment]
@akrigator 
You should be able to go to the Configure Settings > Data Sources > Apple Account Username/Password screen, select your account, edit the current password, select Login... and Submit. It will validate it and update the config files with the new p/w.

**Comment by Darkwulf183** [comment]
short info I'm out. I bought the HA Cloud solution and use the original app solution. I'm going to assign a new branch to the original app for the automations and see when Icloud 3 starts running properly again. As I control heating and hot water including setback temperatures via the geo positions, I can't wait any longer. Just to let you know that I can't and won't test anything for the time being. Thanks anyway for your effort. :-)

**Comment by JtwoA** [comment]
> short info I'm out. I bought the HA Cloud solution and use the original app solution. I'm going to assign a new branch to the original app for the automations and see when Icloud 3 starts running properly again. As I control heating and hot water including setback temperatures via the geo positions, I can't wait any longer. Just to let you know that I can't and won't test anything for the time being. Thanks anyway for your effort. :-)

4th grade called:  they miss you.  Please bring the ball back.

Seriously, I understand criticality, I just went thru this with local APIs from my Wx stations as I drive HVAC both with conditions provided from those as well as presence.  

**But _dude_**... this is a change by Apple and Gary is not a paid dev for HA, Apple, or anyone else.  He's a retired developer who has given a metric sxxx ton of his personal time to write, maintain, and support this integration.  His responsiveness is better than most paid software.

Responses like yours are what lead to devs like Gary saying "I don't need this abuse" and stopping work on integrations like this.  Please think before responding just how your response comes across.

**Comment by Darkwulf183** [comment]
Hi @JtwoA , I absolutely understand what you mean. My intention was in no way to belittle gary's work. I have the utmost respect for his work. I just wanted to inform you with the thread that I won't be testing any further for the time being. I don't have the time at the moment and we have 0 degrees in my corner of Germany almost every night, so I need a functioning heating system... that's all it was. He is outstanding with his work that he has tackled the whole issue in this way. Sorry if that came across differently.

**Comment by gcobb321** [comment]
### iCloud3 v3.1.1 has been to HACS

Release page is [here](https://github.com/gcobb321/icloud3_v3/releases)

### Change Log - v3.1.1
1. LOCATING DEVICES:
    - Added additional checks to insure the Apple Account location data was refreshed during startup and while configuing iCloud3 settings. Fixed a problem where the location information data from Apple was not being initialized properly.
    - Fixed the location refresh not being done that caused the '0 of 0' to be displayed in the Configure Setting screens, leading to the Apple Account selection lists to not be populated.
    - Fixed some problems where 'Locate All Devices = False' would still locate all the devices in the Apple account
    - Added error checking to make sure the Locate All Devices can not be disabled if there were Family devices that
    were assigned to that Apple account. If it was disabled, they would never be located.
2. UPDATE DEVICE SCREEN - Added (and fixed) the TOOLS - RESET DATA SOURCE(S), DELETE DEVICE(S) option where you can reset the device's Apple Account and Mobile App to default values (None) and fixed a problem deleting devices. Reworked the Apple Account selection list to provide more information and identify setup errors.
3. UPDATE APPLE ACCOUNT USERNAME/PASSWORD SCREEN - Added checks to insure Locating All Devices can not be disabled if there are tracked devices assigned to this account that are in the Family list.
4. OTHER THINGS - Changed several things under the covers.

**Comment by gcobb321** [comment]
@Darkwulf183 
I think v3.1.1 fixes a bunch of stuff. I understand you need things to work 100% (well maybe 99%). Apple really screwed me up, as you can imagine. I had not planned on releasing v3.1 this early but it was better working with the new code than trying to implement it in v3.0. That would have been a lot worse and you would have had a poorer experience. Keep an eye on these issues and I'll see you when it settles down.

Gary

**Comment by jspeckman** [comment]
I've install 3.1.1, and after wiping out the stored account information under .storage, I can finally add my account back in.
However when I request a verification code, it never comes through, and this error message in the icloud3-0.log

11-07 14:21:42 iCloud3 v3.1.1
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 655, in __init__
    self.authenticate()
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 827, in authenticate
    raise PyiCloudFailedLoginException(err_msg)
custom_components.icloud3.support.pyicloud_ic3.PyiCloudFailedLoginException: jspeckman, Authentication Failed, Python SRP Library Credentials Error. The Python module that creates the Secure Remote Password hash key has calculated an incorrect value for a valid Username/Password. Try changing the Password to see if the Apple Acct can be logged into. ErrorCode-401

**Comment by gcobb321** [comment]
@jspeckman
See my note [here]{https://github.com/gcobb321/icloud3_v3/issues/341#issuecomment-2458440469} about the password problem.  Changing it has worked for others.

**Comment by Darkwulf183** [comment]
> @Darkwulf183 
> 
> I think v3.1.1 fixes a bunch of stuff. I understand you need things to work 100% (well maybe 99%). Apple really screwed me up, as you can imagine. I had not planned on releasing v3.1 this early but it was better working with the new code than trying to implement it in v3.0. That would have been a lot worse and you would have had a poorer experience. Keep an eye on these issues and I'll see you when it settles down.
> 
> 
> 
> Gary

Gary you are a real role model for me, I started to get into programming stories in 2007 at the technical school for mechanical engineering. If I ever get 20 percent of what you can do, then I'll take my hat off to myself. People like you are the absolute top hammer for me. As soon as there is something to test, I can now test freely. I deactivated iCloud 3 for the time being. I used the evening to clean everything to the cloud solution, i.e. to replace all the sensors. So now I can also test freely. If something breaks, it's no big deal. Thank you again for your time and the work you put into the project, such people are becoming increasingly rare.  Thank you very much 😄

**Comment by gcobb321** [comment]
@de5013
I monitor the HACS data file every 15-minutes for a version change. I’m not sure when HACS updates its files.  The notification should come once HACS does that. Feel free to install it other ways. Over be patient.

Gary Cobb, aka geekstergary
________________________________

**Comment by gcor71** [comment]
v3.1.1 - working beautifully (thank you!).
Except... when using the MAP card where I've added 4 iCloud3 entities "device_tracker.xxxx_phone".
The 'Name' in the Map icons stays blank - it would show initials in the map circle.  The icon is in the right location on the map.  An unrelated 'KL' device_tracker from another integration displays correctly.
I can't see where in my iCloud3 entities to add/update to expose the name to the Map card.
Previously (before the glitch) it worked fine.

Thoughts / pointers?

<img width="992" alt="image" src="https://github.com/user-attachments/assets/dc882527-4955-46c3-8211-fad20a439d18">

**Comment by garyak** [comment]
Do you have entries in your customize.yaml file for the IC3 entities?

```
device_tracker.xxxx_phone:
  entity_picture: /local/xxxxx.jpg
  friendly_name: Rebecca
```

**Comment by garyak** [comment]
customize.yaml is the "old school" way to configure entities. You can perform the same functions using the UI now. Select entities from the iCloud3 integration to configure naming, icon, etc.

The easiest way to clear your current IC3 installation would be to restore a backup from before you attempted the first IC3 installation.  However, you may not need to start from scratch. If the integration remains available on the UI, you could walk through the configuration again looking for and correcting errors. Confirm your icloud account at Apple lists all the devices you wish to track and that each device is setup for Find My. I've setup Family Share for myself and my spouse so only one icloud account needs to be verified.

**Comment by gcor71** [comment]
I’ll give it a try, thank you!

Sent from my iPhone

On 14 Nov 2024, at 15:17, Gary Kelley ***@***.***> wrote:

﻿

customize.yaml is the "old school" way to configure entities. You can perform the same functions using the UI now. Select entities from the iCloud3 integration to configure naming, icon, etc.

The easiest way to clear your current IC3 installation would be to restore a backup from before you attempted the first IC3 installation. However, you may not need to start from scratch. If the integration remains available on the UI, you could walk through the configuration again looking for and correcting errors. Confirm your icloud account at Apple lists all the devices you wish to track and that each device is setup for Find My. I've setup Family Share for myself and my spouse so only one icloud account needs to be verified.

**Comment by gcor71** [comment]
> The easiest way to clear your current IC3 installation would be to restore a backup from before you attempted the first IC3 installation. 

Thanks Gary.  I am having seemingly endless problems with my installation.  Sign-in takes an eternity - and the UI wont recognise successful login (the logs confirm it's OK), neither does the UI recognise successful validation code (again, log confirms OK).  A couple of times I have nudged it along and got IC3 to take me to device configuration, but I'm not being presented with my device or any of my family sharing devices.

I have deleted and recreated the integration.  I have tried several of the fixes shared during the recent issue investigation.  I have reviewed the IC3 logs but they don't obviously flag an error.

To confirm, i am trying to register one iCloud account (my own).  My account has FindMy sharing with 3 members of my family (working 100% on iPhone).

It feels like something is fundamentally wrong with my install and - before I undertake further investigation - I'd like to do a 100% clean re-install of IC3.  Can you confirm the steps needed to do this? Which files and directories need removing? 
 In other posts you've pointed to removing /icloud, /icloud3, .storage/icloud3.apple_acct ...  any others?  I do not have a backup to fall back to.

Thanks in advance for your support.  I very much hope it's all user error on my part! ;-)

**Comment by gcobb321** [comment]
The directories are:
- /icloud3 - iCloud3 program files, Delete iCloud3 integration before you do this. 
- .storage/icloud3 - Configuration files
- .storage/icloud3.apple_acct - Apple login cookies and session files
- .storage/icloud - Old Apple acct cookies and session files (also used by the iCloud integration if it is installed)

**Comment by t077584** [comment]
Hi Gary. I have a rather odd question and maybe it's not even an issue. But it's related to my wife and if the WAF is at stake, I run ;-) I have my garage door use case linked to your solution and for me, it works fine in most of the cases. Turns out that my wife complains, that whenever she comes home, the garage doesn't open and she had to wait for hours. Well, seconds, but you know how this is. 

Today, we came home together (in the same car) and I used this opportunity, to compare the log entires. I see that her phone is checking in at home zone few seconds after mine, but I'm not good in reading and understanding the log very well hence I appreciated your support in how to solve this (if it can be solved at at all). The file is attached. Thx a lot for your support. Much appreciated. Cheers, Mike
[icloud3-event-log_2024.1116-18.08.log](https://github.com/user-attachments/files/17787395/icloud3-event-log_2024.1116-18.08.log)

**Comment by Jinkler** [comment]
Hi all. I've been trying to get this working on and off unsuccessfully. I'm relatively new to HA so this is all a learning curve for me at the moment. I'm running the latest version of HA and iCloud on a raspberry PI. I have an apple account (although don't own any apple devices, the kids and missus do) and I only use this account so I can login to the apple "find me" website to see where my kids are. 

So with this icloud app, I have logged in with my credentials, but it says 0 of 0 iCloud Devices Tracked, Tracked-(), Untracked-().   When I try to add a device, it keeps giving me this message "The configured device was not found in any of the Apple Accounts" on the "update icloud 3 device" page.

And then I keep going around in circles!

Any ideas / pointers please guys?

**Comment by JtwoA** [comment]
> Hi all. I've been trying to get this working on and off unsuccessfully. I'm relatively new to HA so this is all a learning curve for me at the moment. I'm running the latest version of HA and iCloud on a raspberry PI. I have an apple account (although don't own any apple devices, the kids and missus do) and I only use this account so I can login to the apple "find me" website to see where my kids are.
> 
> So with this icloud app, I have logged in with my credentials, but it says 0 of 0 iCloud Devices Tracked, Tracked-(), Untracked-(). When I try to add a device, it keeps giving me this message "The configured device was not found in any of the Apple Accounts" on the "update icloud 3 device" page.
> 
> And then I keep going around in circles!
> 
> Any ideas / pointers please guys?

Please ensure you are installing v3.0.5.9 and nothing later.  Review the open issues for details on Apple changes.

**Comment by gcobb321** [comment]
@Jinkler 
See [here](https://github.com/gcobb321/icloud3_v3/issues/378#issue-2695328791) for more information about this problem

**Comment by Jinkler** [comment]
Thanks! Currently trying that now, but the 6-digit verification code isn't coming through, I've tried re-requesting it a number of times. (Note, I do not own any apple devices, but I do have an apple account, if that makes a difference).

**Comment by gonzonia** [comment]
I want to see if I'm misunderstanding how this should work. When I add my account, should I see family members that share their locations with me?

**Comment by gcobb321** [comment]
The Family members will be listed in the iCloud device selection list on the _Configure > iCloud3 Update Devices_ screen for the iCloud3 devices you are adding. They are also listed on the _Event Log_, Start up Stage 4.

**Comment by gonzonia** [comment]
Eventually the other family members started showing up so I could add them. I added all 3 but only 1 actually tracks and updates (HA has been restarted multiple times). I'm guessing it's probably a setting on their phones preventing the tracking (even though I can see them in FindMy). What should I check? I'm trying to do this without installing the HA app on their phones (none of the 3 family members currently have it installed)

**Comment by gcobb321** [comment]
@gonzonia 
Make sure location sharing is enabled on all of the devices and you have enabled 'Locate All Devices' on the _Update Apple Acct Username/Password_ screen. 

See the iCloud3 docs [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/0.3-apple-account?id=enable-location-sharing) for a note about enabling the location on the devices.

**Comment by gonzonia** [comment]
Thanks. It's working now.
