### ISSUE TITLE
Country Code issue in beta 8a

### ISSUE THREAD

**Issue by B-Hartley** [gcobb321/icloud3_v3#37]
I don't think I can see a solution above.... Is there a forum I should be posting in for questions.  Just installed the beta.  It seems to be having problems with my country code..

It is set on config.yaml

```
homeassistant:
  country: GB

```
```
2023-01-16 19:29:10.185 ERROR (MainThread) [homeassistant.setup] Error during setup of component icloud3
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
    result = await task
  File "/config/custom_components/icloud3/__init__.py", line 74, in async_setup
    v2v3_config_migration.convert_v2_config_files_to_v3()
  File "/config/custom_components/icloud3/support/v2v3_config_migration.py", line 179, in convert_v2_config_files_to_v3
    self._set_data_fields_from_config_parameter_dictionary()
  File "/config/custom_components/icloud3/support/v2v3_config_migration.py", line 570, in _set_data_fields_from_config_parameter_dictionary
    Gb.conf_general[CONF_WAZE_REGION]                = WAZE_SERVERS_BY_COUNTRY_CODE.get(Gb.ha_country_code, 'row')
AttributeError: type object 'GlobalVariables' has no attribute 'ha_country_code'
```

Please advise.

**Comment by gcobb321** [comment]
I just uploaded Beta 8b to fix this.

Download from the [Release page here](https://github.com/gcobb321/icloud3_v3/releases). Select Assets, then select icloud3-beta-8b.zip. Click download on the right side of the screen.

**Comment by B-Hartley** [comment]
Sorry to say, it doesn't seem to have fixed the issue.
I deleted the icloud3 folder from custom_components.
Copied in the new one from the 8b beta zip file.
restarted multiple times.

Still getting the same error messages.........

```
2023-01-17 08:26:21.502 WARNING (MainThread) [icloud3] iCloud3 - Migrating Configuration Parameters
2023-01-17 08:26:21.504 ERROR (MainThread) [homeassistant.setup] Error during setup of component icloud3
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
    result = await task
  File "/config/custom_components/icloud3/__init__.py", line 74, in async_setup
    v2v3_config_migration.convert_v2_config_files_to_v3()
  File "/config/custom_components/icloud3/support/v2v3_config_migration.py", line 179, in convert_v2_config_files_to_v3
    self._set_data_fields_from_config_parameter_dictionary()
  File "/config/custom_components/icloud3/support/v2v3_config_migration.py", line 570, in _set_data_fields_from_config_parameter_dictionary
    Gb.conf_general[CONF_WAZE_REGION]                = WAZE_SERVERS_BY_COUNTRY_CODE.get(Gb.ha_country_code, 'row')
AttributeError: type object 'GlobalVariables' has no attribute 'ha_country_code'
2023-01-17 08:26:21.507 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform icloud3.device_tracker: Unable to set up component.
```
Looking at the file v2v3_config_migration, it still has this line in it....

`        Gb.conf_general[CONF_WAZE_REGION]                = WAZE_SERVERS_BY_COUNTRY_CODE.get(Gb.ha_country_code, 'row')`


I changed this to Gb.country_code and it seemed to fix the problem.
