### ISSUE TITLE
Apple Watch with same name can not be added

### ISSUE THREAD

**Issue by u20p17** [gcobb321/icloud3_v3#51]
Hello,
I am trying to add the apple watch of my father and my own via icloud3 v3. I can only add the watch of my father - when adding my own one I get the following error:
![2](https://user-images.githubusercontent.com/63282286/214383756-a4996713-945d-47e8-bb09-fc8678a30a40.PNG)

I guess this is due to the fact that we both have the same watch (series 6) and we also named it the same (because both are called franz ;) )
![1](https://user-images.githubusercontent.com/63282286/214383906-cb173356-ee2f-429e-b6f7-74e31818c98c.PNG)

Is there a possibility that I can add both watches?

Thank you in advance!

BR

**Comment by gcobb321** [comment]
The iCloud3 devicename can not be the same for 2 devices. You have used applewatch_franz for one device so the other has to be something else; for example: applewatch_franz_son, applewatch_franz_2, etc. The FamShr has Apple Watch von Franz 2 times. Which is OK, just select the correct one to be associated with the watch you are setting up.

I am concerned with the 'Unknown Error Occurred' message. That indicates there was some type of data or code error from the data that was being processed. There should be an error in the home-assistant.log file. Could you look for the error message and post it on this issue page. I may need more data and will let you know.


I might need the icloud3-debug.log file with the debug information to see what was going on and will let you know. I would like to see the debug/rawdata that caused the error if you can make it happen again. To generate that:

To do that:
1. Go to iCloud3 Configurator > Event Log P{arameters > Log Level -- Select RawData.
2. Exit out of the configurator
3. On the Event Log screen, select Restart iCloud3.
4. Go back into the iCloud3 Configurator > iCloud3 Devices and do what you were doing to cause the error.
5. When you are done with the configurator, email the /config/icloud3-debug.log' file to geekstergary@gmail.com. I'll look at it and see what caused the error.

**Comment by u20p17** [comment]
Hi,
thanks for your fast answer. I tried nopw again and got the same error code. Attached the errors I see in the HA log. The debug log I will send to you in the next minutes via mail.

THANK YOU!

```
Logger: icloud3
Source: custom_components/icloud3/support/start_ic3.py:1054
Integration: iCloud3 Device Tracker ([documentation](https://gcobb321.github.io/icloud3_v3_docs/#/), [issues](https://github.com/gcobb321/icloud3/issues))
First occurred: 07:16:34 (2 occurrences)
Last logged: 07:16:57

'Apple Watch von Franz*'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/start_ic3.py", line 1051, in setup_tracked_devices_for_famshr
    _FamShr.device_model_info_by_fname[device_fname]
KeyError: 'Apple Watch von Franz*'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/start_ic3.py", line 1054, in setup_tracked_devices_for_famshr
    f"source-{_FamShr.device_model_info_by_fname[device_fname]}, "
KeyError: 'Apple Watch von Franz*'
```

```
Logger: aiohttp.server
Source: custom_components/icloud3/config_flow.py:2035
Integration: iCloud3 Device Tracker ([documentation](https://gcobb321.github.io/icloud3_v3_docs/#/), [issues](https://github.com/gcobb321/icloud3/issues))
First occurred: 07:17:55 (1 occurrences)
Last logged: 07:17:55

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 241, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 286, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 374, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/icloud3/config_flow.py", line 1876, in async_step_update_device
    user_input  = self._validate_update_device(user_input)
  File "/config/custom_components/icloud3/config_flow.py", line 2035, in _validate_update_device
    raw_model, model, model_display_name = _FamShr.device_model_info_by_fname[conf_famshr_device_fname]
KeyError: 'Apple Watch von Franz*'

```

**Comment by gcobb321** [comment]
I have fixed the problem with more than one device in the Family Share List having the same devicename. The name on the device can be the same but iCloud3 will add (1), (2), etc internally to make the FamShr devicename unique.

Unzip thie zip file into the /icloud3/support directory and restart HA. Check out Stage 4 of the iC3 startup when the iCloud3/FamShr devices are linked.

[duplicate_famshr_names.zip](https://github.com/gcobb321/icloud3_v3/files/10501816/duplicate_famshr_names.zip)

**Comment by u20p17** [comment]
works! thank you very much!

one another thing I recognized: I have added 3 iphones and 2 apple watches in total. When I go to the homeassistant map I only see the location of two iphones. Why not from all devices? What could be here the problem? Thanks!
