### ISSUE TITLE
Stationary Zone did not get setup

### ISSUE THREAD

**Issue by spamsal** [gcobb321/icloud3_v3#71]
Conversation initiated [here](https://community.home-assistant.io/t/icloud3-v2-4-an-advanced-device-tracker-custom-component-that-is-integrated-with-the-ios-app-location-monitor/267554/699?u=spamsal).

`icloud3-debug.log` is just displaying the following repeatedly and nothing else:

```
2023-02-16 16:03:15 [icloud_data_:0086]  ICLOUD >  ::: TRACE ::: kphone_icloud3 Device.icloud_update_reason='Initial Locate@16:03:15',
2023-02-16 16:03:20 [icloud_data_:0086]  ICLOUD >  ::: TRACE ::: kphone_icloud3 Device.icloud_update_reason='Initial Locate@16:03:20',
2023-02-16 16:03:25 [icloud_data_:0086]  ICLOUD >  ::: TRACE ::: kphone_icloud3 Device.icloud_update_reason='Initial Locate@16:03:25',
2023-02-16 16:03:30 [icloud_data_:0086]  ICLOUD >  ::: TRACE ::: kphone_icloud3 Device.icloud_update_reason='Initial Locate@16:03:30',
2023-02-16 16:03:35 [icloud_data_:0086]  ICLOUD >  ::: TRACE ::: kphone_icloud3 Device.icloud_update_reason='Initial Locate@16:03:35',
2023-02-16 16:03:40 [icloud_data_:0086]  ICLOUD >  ::: TRACE ::: kphone_icloud3 Device.icloud_update_reason='Initial Locate@16:03:40',
2023-02-16 16:03:45 [icloud_data_:0086]  ICLOUD >  ::: TRACE ::: kphone_icloud3 Device.icloud_update_reason='Initial Locate@16:03:45',
2023-02-16 16:03:50 [icloud_data_:0086]  ICLOUD >  ::: TRACE ::: kphone_icloud3 Device.icloud_update_reason='Initial Locate@16:03:50',
2023-02-16 16:03:55 [icloud_data_:0086]  ICLOUD >  ::: TRACE ::: kphone_icloud3 Device.icloud_update_reason='Initial Locate@16:03:55',
```

`home-assistant.log` shows this repeatedly:

```
2023-02-16 16:06:25.272 ERROR (SyncWorker_11) [icloud3] 'NoneType' object has no attribute 'update_distance_moved'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/icloud3_main.py", line 771, in process_updated_location_data
    self._check_statzone_timer_expired(Device)
  File "/config/custom_components/icloud3/icloud3_main.py", line 1122, in _check_statzone_timer_expired
    Device.StatZone.update_distance_moved(calc_dist_last_poll_moved_km)
AttributeError: 'NoneType' object has no attribute 'update_distance_moved'
2023-02-16 16:06:25.273 ERROR (SyncWorker_11) [icloud3] Traceback (most recent call last):
  File "/config/custom_components/icloud3/icloud3_main.py", line 771, in process_updated_location_data
    self._check_statzone_timer_expired(Device)
  File "/config/custom_components/icloud3/icloud3_main.py", line 1122, in _check_statzone_timer_expired
    Device.StatZone.update_distance_moved(calc_dist_last_poll_moved_km)
AttributeError: 'NoneType' object has no attribute 'update_distance_moved'

2023-02-16 16:06:30.298 ERROR (SyncWorker_4) [icloud3] '>' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device.py", line 1423, in calculate_old_location_threshold
    if (Gb.old_location_threshold > 0
TypeError: '>' not supported between instances of 'str' and 'int'
2023-02-16 16:06:30.301 ERROR (SyncWorker_4) [icloud3] Traceback (most recent call last):
  File "/config/custom_components/icloud3/device.py", line 1423, in calculate_old_location_threshold
    if (Gb.old_location_threshold > 0
TypeError: '>' not supported between instances of 'str' and 'int'

2023-02-16 16:06:30.308 INFO (SyncWorker_4) [icloud3] ICLOUD >  ::: TRACE ::: kphone_icloud3 Device.icloud_update_reason='Initial Locate@16:06:30', 
2023-02-16 16:06:30.420 ERROR (SyncWorker_4) [icloud3] '>' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device.py", line 1423, in calculate_old_location_threshold
    if (Gb.old_location_threshold > 0
TypeError: '>' not supported between instances of 'str' and 'int'
2023-02-16 16:06:30.431 ERROR (SyncWorker_4) [icloud3] Traceback (most recent call last):
  File "/config/custom_components/icloud3/device.py", line 1423, in calculate_old_location_threshold
    if (Gb.old_location_threshold > 0
TypeError: '>' not supported between instances of 'str' and 'int'

2023-02-16 16:06:30.438 ERROR (SyncWorker_4) [icloud3] 'NoneType' object has no attribute 'update_distance_moved'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/icloud3_main.py", line 771, in process_updated_location_data
    self._check_statzone_timer_expired(Device)
  File "/config/custom_components/icloud3/icloud3_main.py", line 1122, in _check_statzone_timer_expired
    Device.StatZone.update_distance_moved(calc_dist_last_poll_moved_km)
AttributeError: 'NoneType' object has no attribute 'update_distance_moved'
2023-02-16 16:06:30.449 ERROR (SyncWorker_4) [icloud3] Traceback (most recent call last):
  File "/config/custom_components/icloud3/icloud3_main.py", line 771, in process_updated_location_data
    self._check_statzone_timer_expired(Device)
  File "/config/custom_components/icloud3/icloud3_main.py", line 1122, in _check_statzone_timer_expired
    Device.StatZone.update_distance_moved(calc_dist_last_poll_moved_km)
AttributeError: 'NoneType' object has no attribute 'update_distance_moved'
```

As mentioned in the HASS forum, I've had issues with Stationary Zones with v2 as well. I can't say what broke it, but I have not made any changes to HASS since the last time it worked apart from regular updates. I'm unsure if this is related.

**Comment by gcobb321** [comment]
The Debug. Log file has a lot of setup and Configuration info before the msg you posted that shows device, Zone, Stationary zone, etc info.   Set the log level to rawdata and it will also show HA details and location and setup data from iCloud. Then restart HA and send me the file - geekstergary@gmail.com. Then I should be able to see the device and zone data that might show why the error is occurring. 

Thanks

**Comment by gcobb321** [comment]
Closed with b13, Reopen is this is still an issue
