### ISSUE TITLE
Beta14 - Error while setting up icloud3 platform for device_tracker - Home Assistant 2023.3.2 Frontend-versie: 20230306.0 - latest

### ISSUE THREAD

**Issue by mobiledude** [gcobb321/icloud3_v3#84]
Logger: homeassistant.components.device_tracker
Source: components/zone/__init__.py:131
Integration: Apparaattracker (documentation, issues)
First occurred: 05:33:55 (2 occurrences)
Last logged: 05:33:55

Error adding entities for domain device_tracker with platform icloud3
Error while setting up icloud3 platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 717, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 807, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 565, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/config_entry.py", line 254, in state
    zone_state = zone.async_active_zone(
  File "/usr/src/homeassistant/homeassistant/components/zone/__init__.py", line 131, in async_active_zone
    within_zone = zone_dist - radius < zone.attributes[ATTR_RADIUS]
TypeError: unsupported operand type(s) for -: 'float' and 'str'

**Comment by gcobb321** [comment]
I’m going to need some more info to see what is going on. It looks like HA is trying to determine if the device is in a zone. The zone.attributes[ATTR_RADIUS] might be a string field. iCloud3 does not do anything with zone entities but the error says it is setting up a device_tracker entity. 
1. Are there any errors in config/icloud3–debug.log file? You may have to turn on _Log Level Debug_ in the configuration Format Parameters screen. 
2. Does the Event Log show what the device is doing? 
3. Does it happen when HA starts one time or all the time?
4. Is this beta 14 The 3/9/2023 I uploaded this afternoon?
5. Go to Developer tools, select the device_tracker entity that gives the error, scroll back to the top and look at the longitude and latitude. Are they a string in quote marks or a numeric field in red? Is there a gps attribute?
6.

**Comment by gcobb321** [comment]
One more thought. Look at the _.storage/icloud3/restore_state_ file. It has entries for each device. Are any of the latitude or longitude items a string? If so, delete that file and restart HA

**Comment by gcobb321** [comment]
Also:
I just uploaded Beta 14a to fix the _AttributeError: 'iCloud3_DeviceFmZone' object has no attribute 'zone_dist_m'_ error.

https://github.com/gcobb321/icloud3_v3/releases/tag/v3.0.0-beta-14
