### ISSUE TITLE
Reconfigure failure

### ISSUE THREAD

**Issue by kingy444** [gcobb321/icloud3_v3#88]
Woke up this morning to an alert on my phone to reconfigure with a new 2FA token.

Hit allow, got a new token code and tried to enter into HA. The reconfigure failed twice but worked on the third attempt (all attempts used the same code)

Home Assistant 2023.3.3
icloud3 v3.0.0-beta-13

```
2023-03-13 08:31:47.206 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 67, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
result = await method(view, request, data, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
result = await self._async_handle_step(
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/config/custom_components/icloud3/config_flow.py", line 433, in async_step_reauth
valid_code = await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 840, in validate_2fa_code
self.Session.post(f"{self.AUTH_ENDPOINT}/verify/trusteddevice/securitycode",
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
return self.request("POST", url, data=data, json=json, **kwargs)
File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 218, in request
self._raise_error(response.status_code, error_reason)
File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 302, in _raise_error
raise api_error
custom_components.icloud3.support.pyicloud_ic3.PyiCloudAPIResponseException: (Status Code 403)
```

**Comment by gcobb321** [comment]
The error code 403 means the code was not requested  so it might have been accepted on one try but the 2fa indicator was not reset. If you have the icloud3-debug.log file, can you send it to me at geekstergary@gmail.com. There is nothing in the file that relates to security. 

Also, the posting indicates you’re on b13. I just did some major recording related to 2fa in b14.

**Comment by kingy444** [comment]
What do you mean the code wasnt requested? Both HA had RECONFIGURE required and the code request was on my phone?

weird too though -  the debug log is basically empty, should we have something debug enabled by default during the beta? there is also a debug-1 aswell which is basically the exact same from yesterday, about 10 lines of nothing.

and yea i saw b14 was posted but thought i would wait for your response here incase you needed something like this from the b13 code 👍 .

```
2023-03-13 08:33:45 [start_ic3...:0830]  STAGE 2 >  ::: TRACE ::: Zone.name='Away' Zone.fname='Away' Zone.title='Away' Zone.display_as='Away',
2023-03-13 08:33:45 [start_ic3...:0831]  STAGE 2 >  ::: TRACE ::: Gb.zone_display_as={},
2023-03-13 08:33:45 [start_ic3...:0830]  STAGE 2 >  ::: TRACE ::: Zone.name='Notset' Zone.fname='NotSet' Zone.title='Notset' Zone.display_as='NotSet',
2023-03-13 08:33:45 [start_ic3...:0831]  STAGE 2 >  ::: TRACE ::: Gb.zone_display_as={},
2023-03-13 08:33:45 [start_ic3...:0830]  STAGE 2 >  ::: TRACE ::: Zone.name='Stationary' Zone.fname='Stationary' Zone.title='Stationary' Zone.display_as='Stationary',
2023-03-13 08:33:45 [start_ic3...:0831]  STAGE 2 >  ::: TRACE ::: Gb.zone_display_as={},
2023-03-13 08:33:45 [start_ic3...:0830]  STAGE 2 >  ::: TRACE ::: Zone.name='Unknown' Zone.fname='Unknown' Zone.title='Unknown' Zone.display_as='Unknown',
2023-03-13 08:33:45 [start_ic3...:0831]  STAGE 2 >  ::: TRACE ::: Gb.zone_display_as={},

```

**Comment by gcobb321** [comment]
No. I understand it was requested. What I meant was the authentication was accepted by Apple but the interface between iCloud3 and Apple was still flagging it was still needed and displaying the reauthentication required entry notification. 

FYI- When I was looking at the b13 code while working on the b14 update, I saw a bunch of code that did not make sense. I was testing switching accounts in the parameters and authenticating the new account. I had Found some problems where if you changed an iCloud account password in the Configuration Wizard, if the access token was still valid, the password was not invalidating the trust token and access was still granted. I think that issue has been there going back years. That lead to all kinds reverification and correction of these types of coding issues.

**Comment by gcobb321** [comment]
Those TRACE statements in the log was some debug code I missed before publishing b13. The “debug” log level is configured on the Formatting Parameters screen in the Configuration Wizard.

**Comment by kingy444** [comment]
I do get there is a debug setting - I was suggesting the default should be debug while in beta

**Comment by gcobb321** [comment]
Debug now automatically set in betas and for one week after a version upgrade for non-betas. Will be in b15
