### ISSUE TITLE
Travel Time sensor error: ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by Snuffy2** [gcobb321/icloud3_v3#90]
Beta 14b
Got the error and warning below in my HA Logs for the travel time sensor:

```
2023-03-15 20:47:34.821 ERROR (SyncWorker_14) [icloud3] invalid literal for int() with base 10: '1d 1.7h'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/sensor.py", line 1024, in native_value
    if sensor_value == int(sensor_value):
ValueError: invalid literal for int() with base 10: '1d 1.7h'
2023-03-15 20:47:34.851 WARNING (SyncWorker_14) [homeassistant.components.sensor] Sensor sensor.rxxxs_iphone_travel_time has device class None, state class None and unit min thus indicating it has a numeric value; however, it has the non-numeric value: 1d 1.7h (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
```

icloud3 Debug logs from the same time
```
2023-03-15 20:47:30 [icloud3_main:0531]  PREFETCH > rxxxx_iphone > iCloud Location Requested (prefetch)
2023-03-15 20:47:30 [pyicloud_ic3:1566]  PREFETCH >  FmF iCloudData Update RequestedBy-rxxxx_iphone
													    • axxxx_iphone, 8:47:03p/8m
													    • kxxxx_iphone, 8:47:03p/5m
													    • rxxxx_iphone, 8:47:03p/35m *
													    • gxxxx_iphone, 8:47:03p/7m
													    • qxxxx_iphone, 8:47:03p/5m
													    • txxxx_iphone, 8:47:03p/36m
2023-03-15 20:47:30 [icloud_data_:0423]  LOCDATA > jxxxx_iphone > Old Loc FamShr-8:41:27p/±6m (iOSApp-7:29:54p), UpdateIn-5 secs
2023-03-15 20:47:30 [icloud_data_:0423]  LOCDATA > kxxxx_iphone > Updated FmF-8:47:03p/±5m (FamShr-8:41:30p, iOSApp-7:18:37p)
2023-03-15 20:47:30 [icloud_data_:0423]  LOCDATA > qxxxx_iphone > Updated FmF-8:47:03p/±5m (FamShr-8:41:27p, iOSApp-6:41:20p)
2023-03-15 20:47:30 [icloud_data_:0423]  LOCDATA > axxxx_iphone > Updated FmF-8:47:03p/±8m (FamShr-8:41:23p, iOSApp-4:06:46p)
2023-03-15 20:47:30 [icloud_data_:0423]  LOCDATA > gxxxx_iphone > Updated FmF-8:47:03p/±7m
2023-03-15 20:47:30 [device......:1711]  LOCDATA > rxxxx_iphone > Updated (FmF) > 7:12:17p/±8m → 8:47:03p/±35m, Located-28 sec ago, Moved-47 m
2023-03-15 20:47:30 [icloud_data_:0423]  LOCDATA > rxxxx_iphone > Updated FmF-8:47:03p/±35m
2023-03-15 20:47:30 [icloud_data_:0423]  LOCDATA > txxxx_iphone > Updated FmF-8:47:03p/±36m
2023-03-15 20:47:30 [icloud3_main:0537]  PREFETCH > rxxxx_iphone > ────▲─△─▲──── ▷▷ ICLOUD PREFETCH ◁◁ RXXXX_IPHONE, CURRZONE-RXXX_STATIONARY,  ────▲─△─▲────
2023-03-15 20:47:30 [icloud_data_:0421]  LOCDATA > rxxxx_iphone > Updated FmF-8:47:03p/±35m
2023-03-15 20:47:30 [icloud3_main:0431]  ICLOUD > rxxxx_iphone > Trigger > Initial Locate@20:47:30
2023-03-15 20:47:30 [icloud_data_:0421]  LOCDATA > rxxxx_iphone > Updated FmF-8:47:03p/±35m
2023-03-15 20:47:30 [icloud3_main:0710]  ICLOUD > rxxxx_iphone > ────▼─▽─▼──── ▷▷ ICLOUD ◁◁ RXXXX_IPHONE, CURRZONE-RXXX_STATIONARY, INITIAL LOCATE@20:47:30 ────▼─▽─▼────
2023-03-15 20:47:30 [icloud_data_:0421]  LOCDATA > rxxxx_iphone > Updated FmF-8:47:03p/±35m
2023-03-15 20:47:30 [icloud3_main:0861]  ICLOUD > rxxxx_iphone > iCloud update started > Initial Locate@20:47:30
2023-03-15 20:47:30 [icloud3_main:1059]  ICLOUD > rxxxx_iphone > Zone > Home-18 m/r100m, GPS-(41.02347, -74.14121/±35m)
2023-03-15 20:47:30 [icloud3_main:1065]  ICLOUD > rxxxx_iphone > Zone > Home >  Home-18 m,  Axxxx Library-759 m,  Bxxxx School-800 m,  Hxxxx School-868 m,  Cxxxx Lake-1.27 km,  Northern Hxxxx School-1.38 km,  OTF Wxxxx-2.59 km,  OTF Rxxxx-4.80 km,  Rxxxx College Pool-7.17 km,  OTF Mxxxx / Wegmans-7.42 km,  Hxxxx Hospital-28.8 km,  Txxxx Home-139.4 km,  Gxxxx Home-140.6 km,  Cxxxx Home-142.5 km,  Sxxxx Gxxxx Home-150.4 km,  Mxxxx Home-363.0 km
2023-03-15 20:47:30 [determine_in:1240]  ICLOUD > rxxxx_iphone > Check Nearby Device-jxxxx_iphone, CanUse, Cnt-1, Timer-1 secs, jxxxx_iphone → txxxx_iphone → None
2023-03-15 20:47:30 [determine_in:1240]  ICLOUD > rxxxx_iphone > Check Nearby Device-kxxxx_iphone, CanUse, Cnt-1, Timer-1 secs, kxxxx_iphone → txxxx_iphone → None
2023-03-15 20:47:30 [determine_in:1231]  ICLOUD > rxxxx_iphone > Check Nearby Device-qxxxx_iphone, Checking, Cnt-1, Timer-1 secs, qxxxx_iphone → jxxxx_iphone → txxxx_iphone
2023-03-15 20:47:30 [determine_in:1240]  ICLOUD > rxxxx_iphone > Check Nearby Device-qxxxx_iphone, CanNotUse, Looped back to itself, Cnt-2, Timer-1 secs, qxxxx_iphone → jxxxx_iphone → txxxx_iphone → qxxxx_iphone
2023-03-15 20:47:30 [determine_in:1231]  ICLOUD > rxxxx_iphone > Check Nearby Device-axxxx_iphone, Checking, Cnt-1, Timer-1 secs, axxxx_iphone → jxxxx_iphone → txxxx_iphone
2023-03-15 20:47:30 [determine_in:1240]  ICLOUD > rxxxx_iphone > Check Nearby Device-axxxx_iphone, CanNotUse, Looped back to itself, Cnt-2, Timer-1 secs, axxxx_iphone → jxxxx_iphone → txxxx_iphone → axxxx_iphone
2023-03-15 20:47:30 [determine_in:1168]  ICLOUD > rxxxx_iphone > Nearby Devices (<15m) > ⊗Jxxxx/iPhone-20.95m/±6m, ⊗Kxxxx/iPhone-24.037m/±5m, ⊗Qxxxx/iPhone-32.003m/±5m⌘, ⊗Axxxx/iPhone-25.134m/±8m⌘, ⊗Gxxxx/iPhone-140.6km/±7m±, ⊗Txxxx/iPhone-31.785m/±35m±
2023-03-15 20:47:30 [icloud3_main:0933]  ICLOUD > rxxxx_iphone > ────▼─▽─▼──── ▷▷ FMF ◁◁ RXXXX_IPHONE, CURRZONE-RXXX_STATIONARY, HOME ────▼─▽─▼────
2023-03-15 20:47:30 [determine_in:0161]  ICLOUD > rxxxx_iphone > DistFmZome-0, Moved-0, Waze-0, Calc-0.017758, TravTime-1542.806735, Dir-InZone
2023-03-15 20:47:30 [determine_in:0549]  ICLOUD > rxxxx_iphone > Results: From-Home > NextUpdate-10:47:30p, Interval-2 hrs, Method-1.EnterZone
2023-03-15 20:47:30 [determine_in:0570]  [rxxxx_iphone] Tracking Results: From-Home > iOSAppZone-not_set, iC3Zone-home, Interval-2 hrs, TravTime-, Dist-0 mi, NextUpdt-10:47:30p, MaxDist-0 mi, Dir-InZone, Moved-0 m, Battery-0%, LastDataUpdate-8:47:30p, GPSAccuracy-35m, LocAge-28 sec ago, OldThreshold-2 min, LastEvLogMsg-8:47:30p, Method-1.EnterZone
2023-03-15 20:47:30 [icloud3_main:0933]  ICLOUD > rxxxx_iphone > ────▼─▽─▼──── ▷▷ FMF ◁◁ RXXXX_IPHONE, CURRZONE-RXXX_STATIONARY, CXXXXHOME ────▼─▽─▼────
2023-03-15 20:47:30 [waze_history:0354]  ICLOUD > rxxxx_iphone > WazeHistDB > Get All Records, Table-locations, Criteria- lat_long_key='41.0235:-74.1412', RecdCnt-0
2023-03-15 20:47:32 [waze_route_c:0167]  Waze Results > GPS-(74.02347, -41.14121) --> (74.83878, -39.78558), Time-108.80min, Distance-170.44km
2023-03-15 20:47:34 [waze_route_c:0167]  Waze Results > GPS-(81.42655, -28.31541) --> (74.02347, -41.14121), Time-969.55min, Distance-1776.64km
2023-03-15 20:47:34 [waze........:0228]  ICLOUD > rxxxx_iphone > Waze Route Info > TravTime-1.8 hrs, Dist-170.4 km, WazeMoved-1776.6 km, CalcMoved-1542.8 km, Took-3.94 secs
2023-03-15 20:47:34 [determine_in:0161]  ICLOUD > rxxxx_iphone > DistFmZome-170.442, Moved-1776.643, Waze-170.442, Calc-142.460174, TravTime-108.8, Dir-InZone
2023-03-15 20:47:34 [determine_in:0549]  ICLOUD > rxxxx_iphone > Results: From-Cxxxx Home > NextUpdate-10:47:30p, Interval-2 hrs, TravTime-1.8 hrs, Distance-105.9 mi, Method-1.EnterZone
2023-03-15 20:47:34 [determine_in:0570]  [rxxxx_iphone] Tracking Results: From-Cxxxx Home > iOSAppZone-not_set, iC3Zone-home, Interval-2 hrs, TravTime-1.8 hrs, Dist-105.9 mi, NextUpdt-10:47:30p, MaxDist-105.9 mi, Dir-InZone, Moved-0 m, Battery-0%, LastDataUpdate-8:47:30p, GPSAccuracy-35m, LocAge-32 sec ago, OldThreshold-2 min, LastEvLogMsg-8:47:34p, Method-1.EnterZone
2023-03-15 20:47:34 [icloud3_main:0939]  ICLOUD > rxxxx_iphone > ────▲─△─▲──── ▷▷ FMF ◁◁ RXXXX_IPHONE, CURRZONE-RXXX_STATIONARY, CXXXXHOME ────▲─△─▲────
2023-03-15 20:47:34 [icloud3_main:0870]  ICLOUD > rxxxx_iphone > iCloud update completed > Date source - FmF
2023-03-15 20:47:34 [sensor......:1027]  Traceback (most recent call last):
  File "/config/custom_components/icloud3/sensor.py", line 1024, in native_value
    if sensor_value == int(sensor_value):
ValueError: invalid literal for int() with base 10: '1d 1.7h'
2023-03-15 20:47:34 [icloud3_main:1367]  ICLOUD > rxxxx_iphone > Device Monitor > fmf, Initial Locate@20:47:30, AttrsZone-home, LocDataZone-home, Located-8:47:03p (32 sec ago), iOSAppGPS-(0.00000, 0.00000), iOSAppState-not_set), GPS-(41.02347, -74.14121/±35m)
2023-03-15 20:47:34 [icloud3_main:0827]  ICLOUD > rxxxx_iphone > ────▲─△─▲──── ▷▷ FMF/FMF ◁◁ RXXXX_IPHONE, CURRZONE-HOME, GEN UPDATE ────▲─△─▲────
```

**Comment by gcobb321** [comment]
Changed the initial value of some sensors to `0` instead of `—-`. They used to be fields with a um on them. In b15.
