### ISSUE TITLE
Lovelace Resources Error starting v3

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3_v3#95]
Tried installing the v3 beta, for some reason it’s crashing my Lovelace dashboard. Anything stick out that looks off?

Logger: homeassistant.components.websocket_api.http.connection
Source: components/lovelace/websocket.py:64
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:00:22 PM (5 occurrences)
Last logged: 10:00:53 PM

[23399686265232] Error handling message: Unknown error (unknown_error) xxxxx from 192.xxx.xx.xxx (Mozilla/5.0 (iPhone; CPU iPhone OS 16_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2023.2 (io.robbie.HomeAssistant; build:2023.444; iOS 16.4.0) Mobile/HomeAssistant, like Safari)
[
Traceback (most recent call last):
File “/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py”, line 26, in _handle_async_response
await func(hass, connection, msg)
File “/usr/src/homeassistant/homeassistant/components/lovelace/websocket.py”, line 64, in websocket_lovelace_resources
await resources.async_load()
AttributeError: ‘ResourceYAMLCollection’ object has no attribute ‘async_load’

**Comment by cappiel** [comment]
Thanks! I fixed the folder www/icloud3, now I'm getting an error with browser_mod. Worked fine prior to installing

2023-03-23 19:40:46.476 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [23014213535488] Error handling message: Unknown error (unknown_error) moose from 192.x.x.x (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/browser_mod/connection.py", line 143, in handle_update
    dev = getBrowser(hass, browserID)
  File "/config/custom_components/browser_mod/browser.py", line 198, in getBrowser
    browsers[browserID] = BrowserModBrowser(hass, browserID)
  File "/config/custom_components/browser_mod/browser.py", line 42, in __init__
    self.update_entities(hass)
  File "/config/custom_components/browser_mod/browser.py", line 71, in update_entities
    _assert_browser_sensor("sensor", "path", "Browser path", icon="mdi:web")
  File "/config/custom_components/browser_mod/browser.py", line 65, in _assert_browser_sensor
    adder = hass.data[DOMAIN][DATA_ADDERS][type]
KeyError: 'sensor'

**Comment by cappiel** [comment]
Solved it! I had to add icloud3-event-log-card.js and module to the Lovelace: config

**Comment by gcobb321** [comment]
As I recall,  browser_mod also updates the Lovelace Resources. I used some code from it in iCloud3. Is the icloud3-event-log-card.js the first entry in the list? If so, HA might have given the first error trying to create the list. I had checked out that possibility but it was a while ago.

**Comment by cappiel** [comment]
looks like I have it about the 5th one down
